// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: organization_service/organization_invoice_settings.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "organization_service";

export interface InvoiceSettings {
  disable_tax: boolean;
  hst_number?: string | undefined;
}

function createBaseInvoiceSettings(): InvoiceSettings {
  return { disable_tax: false, hst_number: "" };
}

export const InvoiceSettings: MessageFns<InvoiceSettings> = {
  encode(message: InvoiceSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.disable_tax !== false) {
      writer.uint32(8).bool(message.disable_tax);
    }
    if (message.hst_number !== undefined && message.hst_number !== "") {
      writer.uint32(18).string(message.hst_number);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InvoiceSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInvoiceSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.disable_tax = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.hst_number = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InvoiceSettings {
    return {
      disable_tax: isSet(object.disableTax) ? globalThis.Boolean(object.disableTax) : false,
      hst_number: isSet(object.hstNumber) ? globalThis.String(object.hstNumber) : "",
    };
  },

  toJSON(message: InvoiceSettings): unknown {
    const obj: any = {};
    if (message.disable_tax !== false) {
      obj.disableTax = message.disable_tax;
    }
    if (message.hst_number !== undefined && message.hst_number !== "") {
      obj.hstNumber = message.hst_number;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InvoiceSettings>, I>>(base?: I): InvoiceSettings {
    return InvoiceSettings.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InvoiceSettings>, I>>(object: I): InvoiceSettings {
    const message = createBaseInvoiceSettings();
    message.disable_tax = object.disable_tax ?? false;
    message.hst_number = object.hst_number ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
