// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: payment_service/transaction.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";
import { Currency, currencyFromJSON, currencyToJSON, currencyToNumber } from "../organization_service/organization";
import { ObjectId } from "../utils/object_id";

export const protobufPackage = "payment_service_transaction";

export enum TransactionStatus {
  Created = "Created",
  Declined = "Declined",
  RefundedDoNotUseAnymore = "RefundedDoNotUseAnymore",
  Processing = "Processing",
  Paid = "Paid",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function transactionStatusFromJSON(object: any): TransactionStatus {
  switch (object) {
    case 1:
    case "Created":
      return TransactionStatus.Created;
    case 2:
    case "Declined":
      return TransactionStatus.Declined;
    case 3:
    case "RefundedDoNotUseAnymore":
      return TransactionStatus.RefundedDoNotUseAnymore;
    case 4:
    case "Processing":
      return TransactionStatus.Processing;
    case 5:
    case "Paid":
      return TransactionStatus.Paid;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TransactionStatus.UNRECOGNIZED;
  }
}

export function transactionStatusToJSON(object: TransactionStatus): string {
  switch (object) {
    case TransactionStatus.Created:
      return "Created";
    case TransactionStatus.Declined:
      return "Declined";
    case TransactionStatus.RefundedDoNotUseAnymore:
      return "RefundedDoNotUseAnymore";
    case TransactionStatus.Processing:
      return "Processing";
    case TransactionStatus.Paid:
      return "Paid";
    case TransactionStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function transactionStatusToNumber(object: TransactionStatus): number {
  switch (object) {
    case TransactionStatus.Created:
      return 1;
    case TransactionStatus.Declined:
      return 2;
    case TransactionStatus.RefundedDoNotUseAnymore:
      return 3;
    case TransactionStatus.Processing:
      return 4;
    case TransactionStatus.Paid:
      return 5;
    case TransactionStatus.UNRECOGNIZED:
    default:
      return -1;
  }
}

export enum PaymentType {
  Stripe = "Stripe",
  Cash = "Cash",
  Cheque = "Cheque",
  Card = "Card",
  /** ORGANIZATION_INVOICE - application fee from non-tuition invoice transactions (deferred bassemlabs fee) */
  ORGANIZATION_INVOICE = "ORGANIZATION_INVOICE",
  Other = "Other",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function paymentTypeFromJSON(object: any): PaymentType {
  switch (object) {
    case 1:
    case "Stripe":
      return PaymentType.Stripe;
    case 2:
    case "Cash":
      return PaymentType.Cash;
    case 3:
    case "Cheque":
      return PaymentType.Cheque;
    case 4:
    case "Card":
      return PaymentType.Card;
    case 5:
    case "ORGANIZATION_INVOICE":
      return PaymentType.ORGANIZATION_INVOICE;
    case 6:
    case "Other":
      return PaymentType.Other;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PaymentType.UNRECOGNIZED;
  }
}

export function paymentTypeToJSON(object: PaymentType): string {
  switch (object) {
    case PaymentType.Stripe:
      return "Stripe";
    case PaymentType.Cash:
      return "Cash";
    case PaymentType.Cheque:
      return "Cheque";
    case PaymentType.Card:
      return "Card";
    case PaymentType.ORGANIZATION_INVOICE:
      return "ORGANIZATION_INVOICE";
    case PaymentType.Other:
      return "Other";
    case PaymentType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function paymentTypeToNumber(object: PaymentType): number {
  switch (object) {
    case PaymentType.Stripe:
      return 1;
    case PaymentType.Cash:
      return 2;
    case PaymentType.Cheque:
      return 3;
    case PaymentType.Card:
      return 4;
    case PaymentType.ORGANIZATION_INVOICE:
      return 5;
    case PaymentType.Other:
      return 6;
    case PaymentType.UNRECOGNIZED:
    default:
      return -1;
  }
}

export enum RefundTransactionStatus {
  Pending = "Pending",
  Succeeded = "Succeeded",
  Failed = "Failed",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function refundTransactionStatusFromJSON(object: any): RefundTransactionStatus {
  switch (object) {
    case 1:
    case "Pending":
      return RefundTransactionStatus.Pending;
    case 2:
    case "Succeeded":
      return RefundTransactionStatus.Succeeded;
    case 3:
    case "Failed":
      return RefundTransactionStatus.Failed;
    case -1:
    case "UNRECOGNIZED":
    default:
      return RefundTransactionStatus.UNRECOGNIZED;
  }
}

export function refundTransactionStatusToJSON(object: RefundTransactionStatus): string {
  switch (object) {
    case RefundTransactionStatus.Pending:
      return "Pending";
    case RefundTransactionStatus.Succeeded:
      return "Succeeded";
    case RefundTransactionStatus.Failed:
      return "Failed";
    case RefundTransactionStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function refundTransactionStatusToNumber(object: RefundTransactionStatus): number {
  switch (object) {
    case RefundTransactionStatus.Pending:
      return 1;
    case RefundTransactionStatus.Succeeded:
      return 2;
    case RefundTransactionStatus.Failed:
      return 3;
    case RefundTransactionStatus.UNRECOGNIZED:
    default:
      return -1;
  }
}

export interface Transaction {
  id: ObjectId | undefined;
  organization: ObjectId | undefined;
  stripe_payment_intent_id: string;
  currency: Currency;
  status: TransactionStatus;
  payment_type: PaymentType;
  date: Date | undefined;
  invoice: ObjectId | undefined;
  amount: number;
  declined_reason?: string | undefined;
  processing_fee_amount?:
    | number
    | undefined;
  /** this is for the fixed tuition cost */
  bassem_labs_fee?:
    | number
    | undefined;
  /** this is for the percentage */
  invoice_surcharge?: number | undefined;
}

export interface RefundTransaction {
  id: ObjectId | undefined;
  organization:
    | ObjectId
    | undefined;
  /** The Transaction this Refund is linked to */
  transaction_id:
    | ObjectId
    | undefined;
  /**
   * Optional: If this is a stripe refund, this will include the stripe refund id
   *    Note: For a RefundTransaction to be a stripe refund, the main transaction must be a stripe transaction
   */
  stripe_refund_id?:
    | string
    | undefined;
  /** Status of the refund */
  status: RefundTransactionStatus;
  /** Payment type of the refund, is it stripe or manual payments? */
  payment_type: PaymentType;
  date:
    | Date
    | undefined;
  /** Amount of the refund */
  amount: number;
  /** Reason for the refund */
  reason?: string | undefined;
}

function createBaseTransaction(): Transaction {
  return {
    id: undefined,
    organization: undefined,
    stripe_payment_intent_id: "",
    currency: Currency.USD,
    status: TransactionStatus.Created,
    payment_type: PaymentType.Stripe,
    date: undefined,
    invoice: undefined,
    amount: 0,
    declined_reason: "",
    processing_fee_amount: 0,
    bassem_labs_fee: 0,
    invoice_surcharge: 0,
  };
}

export const Transaction: MessageFns<Transaction> = {
  encode(message: Transaction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      ObjectId.encode(message.id, writer.uint32(10).fork()).join();
    }
    if (message.organization !== undefined) {
      ObjectId.encode(message.organization, writer.uint32(18).fork()).join();
    }
    if (message.stripe_payment_intent_id !== "") {
      writer.uint32(26).string(message.stripe_payment_intent_id);
    }
    if (message.currency !== Currency.USD) {
      writer.uint32(32).int32(currencyToNumber(message.currency));
    }
    if (message.status !== TransactionStatus.Created) {
      writer.uint32(40).int32(transactionStatusToNumber(message.status));
    }
    if (message.payment_type !== PaymentType.Stripe) {
      writer.uint32(48).int32(paymentTypeToNumber(message.payment_type));
    }
    if (message.date !== undefined) {
      Timestamp.encode(toTimestamp(message.date), writer.uint32(58).fork()).join();
    }
    if (message.invoice !== undefined) {
      ObjectId.encode(message.invoice, writer.uint32(66).fork()).join();
    }
    if (message.amount !== 0) {
      writer.uint32(73).double(message.amount);
    }
    if (message.declined_reason !== undefined && message.declined_reason !== "") {
      writer.uint32(82).string(message.declined_reason);
    }
    if (message.processing_fee_amount !== undefined && message.processing_fee_amount !== 0) {
      writer.uint32(89).double(message.processing_fee_amount);
    }
    if (message.bassem_labs_fee !== undefined && message.bassem_labs_fee !== 0) {
      writer.uint32(97).double(message.bassem_labs_fee);
    }
    if (message.invoice_surcharge !== undefined && message.invoice_surcharge !== 0) {
      writer.uint32(105).double(message.invoice_surcharge);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Transaction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransaction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.organization = ObjectId.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.stripe_payment_intent_id = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.currency = currencyFromJSON(reader.int32());
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.status = transactionStatusFromJSON(reader.int32());
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.payment_type = paymentTypeFromJSON(reader.int32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.date = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.invoice = ObjectId.decode(reader, reader.uint32());
          continue;
        case 9:
          if (tag !== 73) {
            break;
          }

          message.amount = reader.double();
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.declined_reason = reader.string();
          continue;
        case 11:
          if (tag !== 89) {
            break;
          }

          message.processing_fee_amount = reader.double();
          continue;
        case 12:
          if (tag !== 97) {
            break;
          }

          message.bassem_labs_fee = reader.double();
          continue;
        case 13:
          if (tag !== 105) {
            break;
          }

          message.invoice_surcharge = reader.double();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Transaction {
    return {
      id: isSet(object.id) ? ObjectId.fromJSON(object.id) : undefined,
      organization: isSet(object.organization) ? ObjectId.fromJSON(object.organization) : undefined,
      stripe_payment_intent_id: isSet(object.stripe_payment_intent_id)
        ? globalThis.String(object.stripe_payment_intent_id)
        : "",
      currency: isSet(object.currency) ? currencyFromJSON(object.currency) : Currency.USD,
      status: isSet(object.status) ? transactionStatusFromJSON(object.status) : TransactionStatus.Created,
      payment_type: isSet(object.payment_type) ? paymentTypeFromJSON(object.payment_type) : PaymentType.Stripe,
      date: isSet(object.date) ? fromJsonTimestamp(object.date) : undefined,
      invoice: isSet(object.invoice) ? ObjectId.fromJSON(object.invoice) : undefined,
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      declined_reason: isSet(object.declined_reason) ? globalThis.String(object.declined_reason) : "",
      processing_fee_amount: isSet(object.processing_fee_amount) ? globalThis.Number(object.processing_fee_amount) : 0,
      bassem_labs_fee: isSet(object.bassem_labs_fee) ? globalThis.Number(object.bassem_labs_fee) : 0,
      invoice_surcharge: isSet(object.invoice_surcharge) ? globalThis.Number(object.invoice_surcharge) : 0,
    };
  },

  toJSON(message: Transaction): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = ObjectId.toJSON(message.id);
    }
    if (message.organization !== undefined) {
      obj.organization = ObjectId.toJSON(message.organization);
    }
    if (message.stripe_payment_intent_id !== "") {
      obj.stripe_payment_intent_id = message.stripe_payment_intent_id;
    }
    if (message.currency !== Currency.USD) {
      obj.currency = currencyToJSON(message.currency);
    }
    if (message.status !== TransactionStatus.Created) {
      obj.status = transactionStatusToJSON(message.status);
    }
    if (message.payment_type !== PaymentType.Stripe) {
      obj.payment_type = paymentTypeToJSON(message.payment_type);
    }
    if (message.date !== undefined) {
      obj.date = message.date.toISOString();
    }
    if (message.invoice !== undefined) {
      obj.invoice = ObjectId.toJSON(message.invoice);
    }
    if (message.amount !== 0) {
      obj.amount = message.amount;
    }
    if (message.declined_reason !== undefined && message.declined_reason !== "") {
      obj.declined_reason = message.declined_reason;
    }
    if (message.processing_fee_amount !== undefined && message.processing_fee_amount !== 0) {
      obj.processing_fee_amount = message.processing_fee_amount;
    }
    if (message.bassem_labs_fee !== undefined && message.bassem_labs_fee !== 0) {
      obj.bassem_labs_fee = message.bassem_labs_fee;
    }
    if (message.invoice_surcharge !== undefined && message.invoice_surcharge !== 0) {
      obj.invoice_surcharge = message.invoice_surcharge;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Transaction>, I>>(base?: I): Transaction {
    return Transaction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Transaction>, I>>(object: I): Transaction {
    const message = createBaseTransaction();
    message.id = (object.id !== undefined && object.id !== null) ? ObjectId.fromPartial(object.id) : undefined;
    message.organization = (object.organization !== undefined && object.organization !== null)
      ? ObjectId.fromPartial(object.organization)
      : undefined;
    message.stripe_payment_intent_id = object.stripe_payment_intent_id ?? "";
    message.currency = object.currency ?? Currency.USD;
    message.status = object.status ?? TransactionStatus.Created;
    message.payment_type = object.payment_type ?? PaymentType.Stripe;
    message.date = object.date ?? undefined;
    message.invoice = (object.invoice !== undefined && object.invoice !== null)
      ? ObjectId.fromPartial(object.invoice)
      : undefined;
    message.amount = object.amount ?? 0;
    message.declined_reason = object.declined_reason ?? "";
    message.processing_fee_amount = object.processing_fee_amount ?? 0;
    message.bassem_labs_fee = object.bassem_labs_fee ?? 0;
    message.invoice_surcharge = object.invoice_surcharge ?? 0;
    return message;
  },
};

function createBaseRefundTransaction(): RefundTransaction {
  return {
    id: undefined,
    organization: undefined,
    transaction_id: undefined,
    stripe_refund_id: "",
    status: RefundTransactionStatus.Pending,
    payment_type: PaymentType.Stripe,
    date: undefined,
    amount: 0,
    reason: "",
  };
}

export const RefundTransaction: MessageFns<RefundTransaction> = {
  encode(message: RefundTransaction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      ObjectId.encode(message.id, writer.uint32(10).fork()).join();
    }
    if (message.organization !== undefined) {
      ObjectId.encode(message.organization, writer.uint32(18).fork()).join();
    }
    if (message.transaction_id !== undefined) {
      ObjectId.encode(message.transaction_id, writer.uint32(26).fork()).join();
    }
    if (message.stripe_refund_id !== undefined && message.stripe_refund_id !== "") {
      writer.uint32(34).string(message.stripe_refund_id);
    }
    if (message.status !== RefundTransactionStatus.Pending) {
      writer.uint32(40).int32(refundTransactionStatusToNumber(message.status));
    }
    if (message.payment_type !== PaymentType.Stripe) {
      writer.uint32(48).int32(paymentTypeToNumber(message.payment_type));
    }
    if (message.date !== undefined) {
      Timestamp.encode(toTimestamp(message.date), writer.uint32(58).fork()).join();
    }
    if (message.amount !== 0) {
      writer.uint32(65).double(message.amount);
    }
    if (message.reason !== undefined && message.reason !== "") {
      writer.uint32(74).string(message.reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefundTransaction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRefundTransaction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.organization = ObjectId.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.transaction_id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.stripe_refund_id = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.status = refundTransactionStatusFromJSON(reader.int32());
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.payment_type = paymentTypeFromJSON(reader.int32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.date = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 8:
          if (tag !== 65) {
            break;
          }

          message.amount = reader.double();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.reason = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RefundTransaction {
    return {
      id: isSet(object.id) ? ObjectId.fromJSON(object.id) : undefined,
      organization: isSet(object.organization) ? ObjectId.fromJSON(object.organization) : undefined,
      transaction_id: isSet(object.transaction_id) ? ObjectId.fromJSON(object.transaction_id) : undefined,
      stripe_refund_id: isSet(object.stripe_refund_id) ? globalThis.String(object.stripe_refund_id) : "",
      status: isSet(object.status) ? refundTransactionStatusFromJSON(object.status) : RefundTransactionStatus.Pending,
      payment_type: isSet(object.payment_type) ? paymentTypeFromJSON(object.payment_type) : PaymentType.Stripe,
      date: isSet(object.date) ? fromJsonTimestamp(object.date) : undefined,
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
    };
  },

  toJSON(message: RefundTransaction): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = ObjectId.toJSON(message.id);
    }
    if (message.organization !== undefined) {
      obj.organization = ObjectId.toJSON(message.organization);
    }
    if (message.transaction_id !== undefined) {
      obj.transaction_id = ObjectId.toJSON(message.transaction_id);
    }
    if (message.stripe_refund_id !== undefined && message.stripe_refund_id !== "") {
      obj.stripe_refund_id = message.stripe_refund_id;
    }
    if (message.status !== RefundTransactionStatus.Pending) {
      obj.status = refundTransactionStatusToJSON(message.status);
    }
    if (message.payment_type !== PaymentType.Stripe) {
      obj.payment_type = paymentTypeToJSON(message.payment_type);
    }
    if (message.date !== undefined) {
      obj.date = message.date.toISOString();
    }
    if (message.amount !== 0) {
      obj.amount = message.amount;
    }
    if (message.reason !== undefined && message.reason !== "") {
      obj.reason = message.reason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RefundTransaction>, I>>(base?: I): RefundTransaction {
    return RefundTransaction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefundTransaction>, I>>(object: I): RefundTransaction {
    const message = createBaseRefundTransaction();
    message.id = (object.id !== undefined && object.id !== null) ? ObjectId.fromPartial(object.id) : undefined;
    message.organization = (object.organization !== undefined && object.organization !== null)
      ? ObjectId.fromPartial(object.organization)
      : undefined;
    message.transaction_id = (object.transaction_id !== undefined && object.transaction_id !== null)
      ? ObjectId.fromPartial(object.transaction_id)
      : undefined;
    message.stripe_refund_id = object.stripe_refund_id ?? "";
    message.status = object.status ?? RefundTransactionStatus.Pending;
    message.payment_type = object.payment_type ?? PaymentType.Stripe;
    message.date = object.date ?? undefined;
    message.amount = object.amount ?? 0;
    message.reason = object.reason ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
