// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: payment_service/tuition_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ObjectId } from "../utils/object_id";
import { RequestContext } from "../utils/request_context";
import {
  AdditionalFee,
  DiscountStackMode,
  discountStackModeFromJSON,
  discountStackModeToJSON,
  discountStackModeToNumber,
  DiscountType,
  discountTypeFromJSON,
  discountTypeToJSON,
  discountTypeToNumber,
  DiscountValueType,
  discountValueTypeFromJSON,
  discountValueTypeToJSON,
  discountValueTypeToNumber,
  PaymentInstallment,
  PaymentScheduleType,
  paymentScheduleTypeFromJSON,
  paymentScheduleTypeToJSON,
  paymentScheduleTypeToNumber,
  Scope,
  scopeFromJSON,
  scopeToJSON,
  scopeToNumber,
  TuitionDiscount,
  TuitionPlan,
  TuitionRate,
} from "./tuition";

export const protobufPackage = "payment_service";

/** TuitionRate messages */
export interface GetTuitionRateRequest {
  context: RequestContext | undefined;
  schoolYear: ObjectId | undefined;
  grade: string;
}

export interface ListTuitionRatesRequest {
  context: RequestContext | undefined;
  schoolYear: ObjectId | undefined;
}

export interface ListTuitionRatesResponse {
  rates: TuitionRate[];
}

export interface GradeAmount {
  grade: string;
  amount: number;
}

export interface UpsertTuitionRatesRequest {
  context: RequestContext | undefined;
  schoolYear: ObjectId | undefined;
  gradeAmounts: GradeAmount[];
}

/** AdditionalFee messages */
export interface GetAdditionalFeeRequest {
  context: RequestContext | undefined;
  id: ObjectId | undefined;
}

export interface ListAdditionalFeesRequest {
  context: RequestContext | undefined;
  schoolYear: ObjectId | undefined;
}

export interface ListAdditionalFeesResponse {
  fees: AdditionalFee[];
}

export interface CreateAdditionalFeeRequest {
  context: RequestContext | undefined;
  schoolYear: ObjectId | undefined;
  name: string;
  description: string;
  amount: number;
  isOptional: boolean;
  scope: Scope;
}

export interface UpdateAdditionalFeeRequest {
  context: RequestContext | undefined;
  id: ObjectId | undefined;
  name: string;
  description: string;
  amount: number;
  isOptional: boolean;
  scope: Scope;
}

export interface DeleteAdditionalFeeRequest {
  context: RequestContext | undefined;
  id: ObjectId | undefined;
}

export interface DeleteAdditionalFeeResponse {
  success: boolean;
}

/** TuitionDiscount messages */
export interface GetTuitionDiscountRequest {
  context: RequestContext | undefined;
  id: ObjectId | undefined;
}

export interface ListTuitionDiscountsRequest {
  context: RequestContext | undefined;
  schoolYear: ObjectId | undefined;
}

export interface ListTuitionDiscountsResponse {
  discounts: TuitionDiscount[];
}

export interface CreateTuitionDiscountRequest {
  context: RequestContext | undefined;
  schoolYear: ObjectId | undefined;
  name: string;
  discountType: DiscountType;
  scope: Scope;
  valueType: DiscountValueType;
  value: number;
  description: string;
  stackMode: DiscountStackMode;
}

export interface UpdateTuitionDiscountRequest {
  context: RequestContext | undefined;
  id: ObjectId | undefined;
  name: string;
  discountType: DiscountType;
  scope: Scope;
  valueType: DiscountValueType;
  value: number;
  description: string;
  stackMode: DiscountStackMode;
}

export interface DeleteTuitionDiscountRequest {
  context: RequestContext | undefined;
  id: ObjectId | undefined;
}

export interface DeleteTuitionDiscountResponse {
  success: boolean;
}

/** TuitionPlan messages */
export interface GetTuitionPlanRequest {
  context: RequestContext | undefined;
  id: ObjectId | undefined;
}

export interface ListTuitionPlansRequest {
  context: RequestContext | undefined;
  schoolYear: ObjectId | undefined;
  archived?: boolean | undefined;
}

export interface ListTuitionPlansResponse {
  plans: TuitionPlan[];
}

export interface CreateTuitionPlanRequest {
  context: RequestContext | undefined;
  schoolYear: ObjectId | undefined;
  name: string;
  description: string;
  scheduleType: PaymentScheduleType;
  numberOfMonths?: number | undefined;
  installments: PaymentInstallment[];
}

export interface UpdateTuitionPlanRequest {
  context: RequestContext | undefined;
  id: ObjectId | undefined;
  name: string;
  description: string;
  scheduleType: PaymentScheduleType;
  numberOfMonths?: number | undefined;
  installments: PaymentInstallment[];
}

export interface ArchiveTuitionPlanRequest {
  context: RequestContext | undefined;
  id: ObjectId | undefined;
}

export interface UnarchiveTuitionPlanRequest {
  context: RequestContext | undefined;
  id: ObjectId | undefined;
}

function createBaseGetTuitionRateRequest(): GetTuitionRateRequest {
  return { context: undefined, schoolYear: undefined, grade: "" };
}

export const GetTuitionRateRequest: MessageFns<GetTuitionRateRequest> = {
  encode(message: GetTuitionRateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.schoolYear !== undefined) {
      ObjectId.encode(message.schoolYear, writer.uint32(18).fork()).join();
    }
    if (message.grade !== "") {
      writer.uint32(26).string(message.grade);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTuitionRateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTuitionRateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.schoolYear = ObjectId.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.grade = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTuitionRateRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      schoolYear: isSet(object.schoolYear) ? ObjectId.fromJSON(object.schoolYear) : undefined,
      grade: isSet(object.grade) ? globalThis.String(object.grade) : "",
    };
  },

  toJSON(message: GetTuitionRateRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.schoolYear !== undefined) {
      obj.schoolYear = ObjectId.toJSON(message.schoolYear);
    }
    if (message.grade !== "") {
      obj.grade = message.grade;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTuitionRateRequest>, I>>(base?: I): GetTuitionRateRequest {
    return GetTuitionRateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTuitionRateRequest>, I>>(object: I): GetTuitionRateRequest {
    const message = createBaseGetTuitionRateRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.schoolYear = (object.schoolYear !== undefined && object.schoolYear !== null)
      ? ObjectId.fromPartial(object.schoolYear)
      : undefined;
    message.grade = object.grade ?? "";
    return message;
  },
};

function createBaseListTuitionRatesRequest(): ListTuitionRatesRequest {
  return { context: undefined, schoolYear: undefined };
}

export const ListTuitionRatesRequest: MessageFns<ListTuitionRatesRequest> = {
  encode(message: ListTuitionRatesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.schoolYear !== undefined) {
      ObjectId.encode(message.schoolYear, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTuitionRatesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTuitionRatesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.schoolYear = ObjectId.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListTuitionRatesRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      schoolYear: isSet(object.schoolYear) ? ObjectId.fromJSON(object.schoolYear) : undefined,
    };
  },

  toJSON(message: ListTuitionRatesRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.schoolYear !== undefined) {
      obj.schoolYear = ObjectId.toJSON(message.schoolYear);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListTuitionRatesRequest>, I>>(base?: I): ListTuitionRatesRequest {
    return ListTuitionRatesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListTuitionRatesRequest>, I>>(object: I): ListTuitionRatesRequest {
    const message = createBaseListTuitionRatesRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.schoolYear = (object.schoolYear !== undefined && object.schoolYear !== null)
      ? ObjectId.fromPartial(object.schoolYear)
      : undefined;
    return message;
  },
};

function createBaseListTuitionRatesResponse(): ListTuitionRatesResponse {
  return { rates: [] };
}

export const ListTuitionRatesResponse: MessageFns<ListTuitionRatesResponse> = {
  encode(message: ListTuitionRatesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.rates) {
      TuitionRate.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTuitionRatesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTuitionRatesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.rates.push(TuitionRate.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListTuitionRatesResponse {
    return {
      rates: globalThis.Array.isArray(object?.rates) ? object.rates.map((e: any) => TuitionRate.fromJSON(e)) : [],
    };
  },

  toJSON(message: ListTuitionRatesResponse): unknown {
    const obj: any = {};
    if (message.rates?.length) {
      obj.rates = message.rates.map((e) => TuitionRate.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListTuitionRatesResponse>, I>>(base?: I): ListTuitionRatesResponse {
    return ListTuitionRatesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListTuitionRatesResponse>, I>>(object: I): ListTuitionRatesResponse {
    const message = createBaseListTuitionRatesResponse();
    message.rates = object.rates?.map((e) => TuitionRate.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGradeAmount(): GradeAmount {
  return { grade: "", amount: 0 };
}

export const GradeAmount: MessageFns<GradeAmount> = {
  encode(message: GradeAmount, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.grade !== "") {
      writer.uint32(10).string(message.grade);
    }
    if (message.amount !== 0) {
      writer.uint32(17).double(message.amount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GradeAmount {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGradeAmount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.grade = reader.string();
          continue;
        case 2:
          if (tag !== 17) {
            break;
          }

          message.amount = reader.double();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GradeAmount {
    return {
      grade: isSet(object.grade) ? globalThis.String(object.grade) : "",
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
    };
  },

  toJSON(message: GradeAmount): unknown {
    const obj: any = {};
    if (message.grade !== "") {
      obj.grade = message.grade;
    }
    if (message.amount !== 0) {
      obj.amount = message.amount;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GradeAmount>, I>>(base?: I): GradeAmount {
    return GradeAmount.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GradeAmount>, I>>(object: I): GradeAmount {
    const message = createBaseGradeAmount();
    message.grade = object.grade ?? "";
    message.amount = object.amount ?? 0;
    return message;
  },
};

function createBaseUpsertTuitionRatesRequest(): UpsertTuitionRatesRequest {
  return { context: undefined, schoolYear: undefined, gradeAmounts: [] };
}

export const UpsertTuitionRatesRequest: MessageFns<UpsertTuitionRatesRequest> = {
  encode(message: UpsertTuitionRatesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.schoolYear !== undefined) {
      ObjectId.encode(message.schoolYear, writer.uint32(18).fork()).join();
    }
    for (const v of message.gradeAmounts) {
      GradeAmount.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpsertTuitionRatesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpsertTuitionRatesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.schoolYear = ObjectId.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.gradeAmounts.push(GradeAmount.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpsertTuitionRatesRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      schoolYear: isSet(object.schoolYear) ? ObjectId.fromJSON(object.schoolYear) : undefined,
      gradeAmounts: globalThis.Array.isArray(object?.gradeAmounts)
        ? object.gradeAmounts.map((e: any) => GradeAmount.fromJSON(e))
        : [],
    };
  },

  toJSON(message: UpsertTuitionRatesRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.schoolYear !== undefined) {
      obj.schoolYear = ObjectId.toJSON(message.schoolYear);
    }
    if (message.gradeAmounts?.length) {
      obj.gradeAmounts = message.gradeAmounts.map((e) => GradeAmount.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpsertTuitionRatesRequest>, I>>(base?: I): UpsertTuitionRatesRequest {
    return UpsertTuitionRatesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpsertTuitionRatesRequest>, I>>(object: I): UpsertTuitionRatesRequest {
    const message = createBaseUpsertTuitionRatesRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.schoolYear = (object.schoolYear !== undefined && object.schoolYear !== null)
      ? ObjectId.fromPartial(object.schoolYear)
      : undefined;
    message.gradeAmounts = object.gradeAmounts?.map((e) => GradeAmount.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetAdditionalFeeRequest(): GetAdditionalFeeRequest {
  return { context: undefined, id: undefined };
}

export const GetAdditionalFeeRequest: MessageFns<GetAdditionalFeeRequest> = {
  encode(message: GetAdditionalFeeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.id !== undefined) {
      ObjectId.encode(message.id, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAdditionalFeeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAdditionalFeeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.id = ObjectId.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAdditionalFeeRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      id: isSet(object.id) ? ObjectId.fromJSON(object.id) : undefined,
    };
  },

  toJSON(message: GetAdditionalFeeRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.id !== undefined) {
      obj.id = ObjectId.toJSON(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAdditionalFeeRequest>, I>>(base?: I): GetAdditionalFeeRequest {
    return GetAdditionalFeeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAdditionalFeeRequest>, I>>(object: I): GetAdditionalFeeRequest {
    const message = createBaseGetAdditionalFeeRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.id = (object.id !== undefined && object.id !== null) ? ObjectId.fromPartial(object.id) : undefined;
    return message;
  },
};

function createBaseListAdditionalFeesRequest(): ListAdditionalFeesRequest {
  return { context: undefined, schoolYear: undefined };
}

export const ListAdditionalFeesRequest: MessageFns<ListAdditionalFeesRequest> = {
  encode(message: ListAdditionalFeesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.schoolYear !== undefined) {
      ObjectId.encode(message.schoolYear, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListAdditionalFeesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAdditionalFeesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.schoolYear = ObjectId.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListAdditionalFeesRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      schoolYear: isSet(object.schoolYear) ? ObjectId.fromJSON(object.schoolYear) : undefined,
    };
  },

  toJSON(message: ListAdditionalFeesRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.schoolYear !== undefined) {
      obj.schoolYear = ObjectId.toJSON(message.schoolYear);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListAdditionalFeesRequest>, I>>(base?: I): ListAdditionalFeesRequest {
    return ListAdditionalFeesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListAdditionalFeesRequest>, I>>(object: I): ListAdditionalFeesRequest {
    const message = createBaseListAdditionalFeesRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.schoolYear = (object.schoolYear !== undefined && object.schoolYear !== null)
      ? ObjectId.fromPartial(object.schoolYear)
      : undefined;
    return message;
  },
};

function createBaseListAdditionalFeesResponse(): ListAdditionalFeesResponse {
  return { fees: [] };
}

export const ListAdditionalFeesResponse: MessageFns<ListAdditionalFeesResponse> = {
  encode(message: ListAdditionalFeesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.fees) {
      AdditionalFee.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListAdditionalFeesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAdditionalFeesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.fees.push(AdditionalFee.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListAdditionalFeesResponse {
    return {
      fees: globalThis.Array.isArray(object?.fees) ? object.fees.map((e: any) => AdditionalFee.fromJSON(e)) : [],
    };
  },

  toJSON(message: ListAdditionalFeesResponse): unknown {
    const obj: any = {};
    if (message.fees?.length) {
      obj.fees = message.fees.map((e) => AdditionalFee.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListAdditionalFeesResponse>, I>>(base?: I): ListAdditionalFeesResponse {
    return ListAdditionalFeesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListAdditionalFeesResponse>, I>>(object: I): ListAdditionalFeesResponse {
    const message = createBaseListAdditionalFeesResponse();
    message.fees = object.fees?.map((e) => AdditionalFee.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCreateAdditionalFeeRequest(): CreateAdditionalFeeRequest {
  return {
    context: undefined,
    schoolYear: undefined,
    name: "",
    description: "",
    amount: 0,
    isOptional: false,
    scope: Scope.STUDENT_SCOPE,
  };
}

export const CreateAdditionalFeeRequest: MessageFns<CreateAdditionalFeeRequest> = {
  encode(message: CreateAdditionalFeeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.schoolYear !== undefined) {
      ObjectId.encode(message.schoolYear, writer.uint32(18).fork()).join();
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(34).string(message.description);
    }
    if (message.amount !== 0) {
      writer.uint32(41).double(message.amount);
    }
    if (message.isOptional !== false) {
      writer.uint32(48).bool(message.isOptional);
    }
    if (message.scope !== Scope.STUDENT_SCOPE) {
      writer.uint32(56).int32(scopeToNumber(message.scope));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateAdditionalFeeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateAdditionalFeeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.schoolYear = ObjectId.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        case 5:
          if (tag !== 41) {
            break;
          }

          message.amount = reader.double();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.isOptional = reader.bool();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.scope = scopeFromJSON(reader.int32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateAdditionalFeeRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      schoolYear: isSet(object.schoolYear) ? ObjectId.fromJSON(object.schoolYear) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      isOptional: isSet(object.isOptional) ? globalThis.Boolean(object.isOptional) : false,
      scope: isSet(object.scope) ? scopeFromJSON(object.scope) : Scope.STUDENT_SCOPE,
    };
  },

  toJSON(message: CreateAdditionalFeeRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.schoolYear !== undefined) {
      obj.schoolYear = ObjectId.toJSON(message.schoolYear);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.amount !== 0) {
      obj.amount = message.amount;
    }
    if (message.isOptional !== false) {
      obj.isOptional = message.isOptional;
    }
    if (message.scope !== Scope.STUDENT_SCOPE) {
      obj.scope = scopeToJSON(message.scope);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateAdditionalFeeRequest>, I>>(base?: I): CreateAdditionalFeeRequest {
    return CreateAdditionalFeeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateAdditionalFeeRequest>, I>>(object: I): CreateAdditionalFeeRequest {
    const message = createBaseCreateAdditionalFeeRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.schoolYear = (object.schoolYear !== undefined && object.schoolYear !== null)
      ? ObjectId.fromPartial(object.schoolYear)
      : undefined;
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.amount = object.amount ?? 0;
    message.isOptional = object.isOptional ?? false;
    message.scope = object.scope ?? Scope.STUDENT_SCOPE;
    return message;
  },
};

function createBaseUpdateAdditionalFeeRequest(): UpdateAdditionalFeeRequest {
  return {
    context: undefined,
    id: undefined,
    name: "",
    description: "",
    amount: 0,
    isOptional: false,
    scope: Scope.STUDENT_SCOPE,
  };
}

export const UpdateAdditionalFeeRequest: MessageFns<UpdateAdditionalFeeRequest> = {
  encode(message: UpdateAdditionalFeeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.id !== undefined) {
      ObjectId.encode(message.id, writer.uint32(18).fork()).join();
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(34).string(message.description);
    }
    if (message.amount !== 0) {
      writer.uint32(41).double(message.amount);
    }
    if (message.isOptional !== false) {
      writer.uint32(48).bool(message.isOptional);
    }
    if (message.scope !== Scope.STUDENT_SCOPE) {
      writer.uint32(56).int32(scopeToNumber(message.scope));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateAdditionalFeeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateAdditionalFeeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        case 5:
          if (tag !== 41) {
            break;
          }

          message.amount = reader.double();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.isOptional = reader.bool();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.scope = scopeFromJSON(reader.int32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateAdditionalFeeRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      id: isSet(object.id) ? ObjectId.fromJSON(object.id) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      isOptional: isSet(object.isOptional) ? globalThis.Boolean(object.isOptional) : false,
      scope: isSet(object.scope) ? scopeFromJSON(object.scope) : Scope.STUDENT_SCOPE,
    };
  },

  toJSON(message: UpdateAdditionalFeeRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.id !== undefined) {
      obj.id = ObjectId.toJSON(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.amount !== 0) {
      obj.amount = message.amount;
    }
    if (message.isOptional !== false) {
      obj.isOptional = message.isOptional;
    }
    if (message.scope !== Scope.STUDENT_SCOPE) {
      obj.scope = scopeToJSON(message.scope);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateAdditionalFeeRequest>, I>>(base?: I): UpdateAdditionalFeeRequest {
    return UpdateAdditionalFeeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateAdditionalFeeRequest>, I>>(object: I): UpdateAdditionalFeeRequest {
    const message = createBaseUpdateAdditionalFeeRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.id = (object.id !== undefined && object.id !== null) ? ObjectId.fromPartial(object.id) : undefined;
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.amount = object.amount ?? 0;
    message.isOptional = object.isOptional ?? false;
    message.scope = object.scope ?? Scope.STUDENT_SCOPE;
    return message;
  },
};

function createBaseDeleteAdditionalFeeRequest(): DeleteAdditionalFeeRequest {
  return { context: undefined, id: undefined };
}

export const DeleteAdditionalFeeRequest: MessageFns<DeleteAdditionalFeeRequest> = {
  encode(message: DeleteAdditionalFeeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.id !== undefined) {
      ObjectId.encode(message.id, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteAdditionalFeeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteAdditionalFeeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.id = ObjectId.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteAdditionalFeeRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      id: isSet(object.id) ? ObjectId.fromJSON(object.id) : undefined,
    };
  },

  toJSON(message: DeleteAdditionalFeeRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.id !== undefined) {
      obj.id = ObjectId.toJSON(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteAdditionalFeeRequest>, I>>(base?: I): DeleteAdditionalFeeRequest {
    return DeleteAdditionalFeeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteAdditionalFeeRequest>, I>>(object: I): DeleteAdditionalFeeRequest {
    const message = createBaseDeleteAdditionalFeeRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.id = (object.id !== undefined && object.id !== null) ? ObjectId.fromPartial(object.id) : undefined;
    return message;
  },
};

function createBaseDeleteAdditionalFeeResponse(): DeleteAdditionalFeeResponse {
  return { success: false };
}

export const DeleteAdditionalFeeResponse: MessageFns<DeleteAdditionalFeeResponse> = {
  encode(message: DeleteAdditionalFeeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteAdditionalFeeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteAdditionalFeeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteAdditionalFeeResponse {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: DeleteAdditionalFeeResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteAdditionalFeeResponse>, I>>(base?: I): DeleteAdditionalFeeResponse {
    return DeleteAdditionalFeeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteAdditionalFeeResponse>, I>>(object: I): DeleteAdditionalFeeResponse {
    const message = createBaseDeleteAdditionalFeeResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseGetTuitionDiscountRequest(): GetTuitionDiscountRequest {
  return { context: undefined, id: undefined };
}

export const GetTuitionDiscountRequest: MessageFns<GetTuitionDiscountRequest> = {
  encode(message: GetTuitionDiscountRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.id !== undefined) {
      ObjectId.encode(message.id, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTuitionDiscountRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTuitionDiscountRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.id = ObjectId.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTuitionDiscountRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      id: isSet(object.id) ? ObjectId.fromJSON(object.id) : undefined,
    };
  },

  toJSON(message: GetTuitionDiscountRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.id !== undefined) {
      obj.id = ObjectId.toJSON(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTuitionDiscountRequest>, I>>(base?: I): GetTuitionDiscountRequest {
    return GetTuitionDiscountRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTuitionDiscountRequest>, I>>(object: I): GetTuitionDiscountRequest {
    const message = createBaseGetTuitionDiscountRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.id = (object.id !== undefined && object.id !== null) ? ObjectId.fromPartial(object.id) : undefined;
    return message;
  },
};

function createBaseListTuitionDiscountsRequest(): ListTuitionDiscountsRequest {
  return { context: undefined, schoolYear: undefined };
}

export const ListTuitionDiscountsRequest: MessageFns<ListTuitionDiscountsRequest> = {
  encode(message: ListTuitionDiscountsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.schoolYear !== undefined) {
      ObjectId.encode(message.schoolYear, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTuitionDiscountsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTuitionDiscountsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.schoolYear = ObjectId.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListTuitionDiscountsRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      schoolYear: isSet(object.schoolYear) ? ObjectId.fromJSON(object.schoolYear) : undefined,
    };
  },

  toJSON(message: ListTuitionDiscountsRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.schoolYear !== undefined) {
      obj.schoolYear = ObjectId.toJSON(message.schoolYear);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListTuitionDiscountsRequest>, I>>(base?: I): ListTuitionDiscountsRequest {
    return ListTuitionDiscountsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListTuitionDiscountsRequest>, I>>(object: I): ListTuitionDiscountsRequest {
    const message = createBaseListTuitionDiscountsRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.schoolYear = (object.schoolYear !== undefined && object.schoolYear !== null)
      ? ObjectId.fromPartial(object.schoolYear)
      : undefined;
    return message;
  },
};

function createBaseListTuitionDiscountsResponse(): ListTuitionDiscountsResponse {
  return { discounts: [] };
}

export const ListTuitionDiscountsResponse: MessageFns<ListTuitionDiscountsResponse> = {
  encode(message: ListTuitionDiscountsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.discounts) {
      TuitionDiscount.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTuitionDiscountsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTuitionDiscountsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.discounts.push(TuitionDiscount.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListTuitionDiscountsResponse {
    return {
      discounts: globalThis.Array.isArray(object?.discounts)
        ? object.discounts.map((e: any) => TuitionDiscount.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListTuitionDiscountsResponse): unknown {
    const obj: any = {};
    if (message.discounts?.length) {
      obj.discounts = message.discounts.map((e) => TuitionDiscount.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListTuitionDiscountsResponse>, I>>(base?: I): ListTuitionDiscountsResponse {
    return ListTuitionDiscountsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListTuitionDiscountsResponse>, I>>(object: I): ListTuitionDiscountsResponse {
    const message = createBaseListTuitionDiscountsResponse();
    message.discounts = object.discounts?.map((e) => TuitionDiscount.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCreateTuitionDiscountRequest(): CreateTuitionDiscountRequest {
  return {
    context: undefined,
    schoolYear: undefined,
    name: "",
    discountType: DiscountType.STANDARD,
    scope: Scope.STUDENT_SCOPE,
    valueType: DiscountValueType.AMOUNT,
    value: 0,
    description: "",
    stackMode: DiscountStackMode.ADDITIVE,
  };
}

export const CreateTuitionDiscountRequest: MessageFns<CreateTuitionDiscountRequest> = {
  encode(message: CreateTuitionDiscountRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.schoolYear !== undefined) {
      ObjectId.encode(message.schoolYear, writer.uint32(18).fork()).join();
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.discountType !== DiscountType.STANDARD) {
      writer.uint32(32).int32(discountTypeToNumber(message.discountType));
    }
    if (message.scope !== Scope.STUDENT_SCOPE) {
      writer.uint32(40).int32(scopeToNumber(message.scope));
    }
    if (message.valueType !== DiscountValueType.AMOUNT) {
      writer.uint32(48).int32(discountValueTypeToNumber(message.valueType));
    }
    if (message.value !== 0) {
      writer.uint32(57).double(message.value);
    }
    if (message.description !== "") {
      writer.uint32(66).string(message.description);
    }
    if (message.stackMode !== DiscountStackMode.ADDITIVE) {
      writer.uint32(72).int32(discountStackModeToNumber(message.stackMode));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateTuitionDiscountRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTuitionDiscountRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.schoolYear = ObjectId.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.discountType = discountTypeFromJSON(reader.int32());
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.scope = scopeFromJSON(reader.int32());
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.valueType = discountValueTypeFromJSON(reader.int32());
          continue;
        case 7:
          if (tag !== 57) {
            break;
          }

          message.value = reader.double();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.description = reader.string();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.stackMode = discountStackModeFromJSON(reader.int32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateTuitionDiscountRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      schoolYear: isSet(object.schoolYear) ? ObjectId.fromJSON(object.schoolYear) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      discountType: isSet(object.discountType) ? discountTypeFromJSON(object.discountType) : DiscountType.STANDARD,
      scope: isSet(object.scope) ? scopeFromJSON(object.scope) : Scope.STUDENT_SCOPE,
      valueType: isSet(object.valueType) ? discountValueTypeFromJSON(object.valueType) : DiscountValueType.AMOUNT,
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      stackMode: isSet(object.stackMode) ? discountStackModeFromJSON(object.stackMode) : DiscountStackMode.ADDITIVE,
    };
  },

  toJSON(message: CreateTuitionDiscountRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.schoolYear !== undefined) {
      obj.schoolYear = ObjectId.toJSON(message.schoolYear);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.discountType !== DiscountType.STANDARD) {
      obj.discountType = discountTypeToJSON(message.discountType);
    }
    if (message.scope !== Scope.STUDENT_SCOPE) {
      obj.scope = scopeToJSON(message.scope);
    }
    if (message.valueType !== DiscountValueType.AMOUNT) {
      obj.valueType = discountValueTypeToJSON(message.valueType);
    }
    if (message.value !== 0) {
      obj.value = message.value;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.stackMode !== DiscountStackMode.ADDITIVE) {
      obj.stackMode = discountStackModeToJSON(message.stackMode);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateTuitionDiscountRequest>, I>>(base?: I): CreateTuitionDiscountRequest {
    return CreateTuitionDiscountRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateTuitionDiscountRequest>, I>>(object: I): CreateTuitionDiscountRequest {
    const message = createBaseCreateTuitionDiscountRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.schoolYear = (object.schoolYear !== undefined && object.schoolYear !== null)
      ? ObjectId.fromPartial(object.schoolYear)
      : undefined;
    message.name = object.name ?? "";
    message.discountType = object.discountType ?? DiscountType.STANDARD;
    message.scope = object.scope ?? Scope.STUDENT_SCOPE;
    message.valueType = object.valueType ?? DiscountValueType.AMOUNT;
    message.value = object.value ?? 0;
    message.description = object.description ?? "";
    message.stackMode = object.stackMode ?? DiscountStackMode.ADDITIVE;
    return message;
  },
};

function createBaseUpdateTuitionDiscountRequest(): UpdateTuitionDiscountRequest {
  return {
    context: undefined,
    id: undefined,
    name: "",
    discountType: DiscountType.STANDARD,
    scope: Scope.STUDENT_SCOPE,
    valueType: DiscountValueType.AMOUNT,
    value: 0,
    description: "",
    stackMode: DiscountStackMode.ADDITIVE,
  };
}

export const UpdateTuitionDiscountRequest: MessageFns<UpdateTuitionDiscountRequest> = {
  encode(message: UpdateTuitionDiscountRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.id !== undefined) {
      ObjectId.encode(message.id, writer.uint32(18).fork()).join();
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.discountType !== DiscountType.STANDARD) {
      writer.uint32(32).int32(discountTypeToNumber(message.discountType));
    }
    if (message.scope !== Scope.STUDENT_SCOPE) {
      writer.uint32(40).int32(scopeToNumber(message.scope));
    }
    if (message.valueType !== DiscountValueType.AMOUNT) {
      writer.uint32(48).int32(discountValueTypeToNumber(message.valueType));
    }
    if (message.value !== 0) {
      writer.uint32(57).double(message.value);
    }
    if (message.description !== "") {
      writer.uint32(66).string(message.description);
    }
    if (message.stackMode !== DiscountStackMode.ADDITIVE) {
      writer.uint32(72).int32(discountStackModeToNumber(message.stackMode));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateTuitionDiscountRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateTuitionDiscountRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.discountType = discountTypeFromJSON(reader.int32());
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.scope = scopeFromJSON(reader.int32());
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.valueType = discountValueTypeFromJSON(reader.int32());
          continue;
        case 7:
          if (tag !== 57) {
            break;
          }

          message.value = reader.double();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.description = reader.string();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.stackMode = discountStackModeFromJSON(reader.int32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateTuitionDiscountRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      id: isSet(object.id) ? ObjectId.fromJSON(object.id) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      discountType: isSet(object.discountType) ? discountTypeFromJSON(object.discountType) : DiscountType.STANDARD,
      scope: isSet(object.scope) ? scopeFromJSON(object.scope) : Scope.STUDENT_SCOPE,
      valueType: isSet(object.valueType) ? discountValueTypeFromJSON(object.valueType) : DiscountValueType.AMOUNT,
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      stackMode: isSet(object.stackMode) ? discountStackModeFromJSON(object.stackMode) : DiscountStackMode.ADDITIVE,
    };
  },

  toJSON(message: UpdateTuitionDiscountRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.id !== undefined) {
      obj.id = ObjectId.toJSON(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.discountType !== DiscountType.STANDARD) {
      obj.discountType = discountTypeToJSON(message.discountType);
    }
    if (message.scope !== Scope.STUDENT_SCOPE) {
      obj.scope = scopeToJSON(message.scope);
    }
    if (message.valueType !== DiscountValueType.AMOUNT) {
      obj.valueType = discountValueTypeToJSON(message.valueType);
    }
    if (message.value !== 0) {
      obj.value = message.value;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.stackMode !== DiscountStackMode.ADDITIVE) {
      obj.stackMode = discountStackModeToJSON(message.stackMode);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateTuitionDiscountRequest>, I>>(base?: I): UpdateTuitionDiscountRequest {
    return UpdateTuitionDiscountRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateTuitionDiscountRequest>, I>>(object: I): UpdateTuitionDiscountRequest {
    const message = createBaseUpdateTuitionDiscountRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.id = (object.id !== undefined && object.id !== null) ? ObjectId.fromPartial(object.id) : undefined;
    message.name = object.name ?? "";
    message.discountType = object.discountType ?? DiscountType.STANDARD;
    message.scope = object.scope ?? Scope.STUDENT_SCOPE;
    message.valueType = object.valueType ?? DiscountValueType.AMOUNT;
    message.value = object.value ?? 0;
    message.description = object.description ?? "";
    message.stackMode = object.stackMode ?? DiscountStackMode.ADDITIVE;
    return message;
  },
};

function createBaseDeleteTuitionDiscountRequest(): DeleteTuitionDiscountRequest {
  return { context: undefined, id: undefined };
}

export const DeleteTuitionDiscountRequest: MessageFns<DeleteTuitionDiscountRequest> = {
  encode(message: DeleteTuitionDiscountRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.id !== undefined) {
      ObjectId.encode(message.id, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteTuitionDiscountRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteTuitionDiscountRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.id = ObjectId.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteTuitionDiscountRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      id: isSet(object.id) ? ObjectId.fromJSON(object.id) : undefined,
    };
  },

  toJSON(message: DeleteTuitionDiscountRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.id !== undefined) {
      obj.id = ObjectId.toJSON(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteTuitionDiscountRequest>, I>>(base?: I): DeleteTuitionDiscountRequest {
    return DeleteTuitionDiscountRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteTuitionDiscountRequest>, I>>(object: I): DeleteTuitionDiscountRequest {
    const message = createBaseDeleteTuitionDiscountRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.id = (object.id !== undefined && object.id !== null) ? ObjectId.fromPartial(object.id) : undefined;
    return message;
  },
};

function createBaseDeleteTuitionDiscountResponse(): DeleteTuitionDiscountResponse {
  return { success: false };
}

export const DeleteTuitionDiscountResponse: MessageFns<DeleteTuitionDiscountResponse> = {
  encode(message: DeleteTuitionDiscountResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteTuitionDiscountResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteTuitionDiscountResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteTuitionDiscountResponse {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: DeleteTuitionDiscountResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteTuitionDiscountResponse>, I>>(base?: I): DeleteTuitionDiscountResponse {
    return DeleteTuitionDiscountResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteTuitionDiscountResponse>, I>>(
    object: I,
  ): DeleteTuitionDiscountResponse {
    const message = createBaseDeleteTuitionDiscountResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseGetTuitionPlanRequest(): GetTuitionPlanRequest {
  return { context: undefined, id: undefined };
}

export const GetTuitionPlanRequest: MessageFns<GetTuitionPlanRequest> = {
  encode(message: GetTuitionPlanRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.id !== undefined) {
      ObjectId.encode(message.id, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTuitionPlanRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTuitionPlanRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.id = ObjectId.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTuitionPlanRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      id: isSet(object.id) ? ObjectId.fromJSON(object.id) : undefined,
    };
  },

  toJSON(message: GetTuitionPlanRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.id !== undefined) {
      obj.id = ObjectId.toJSON(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTuitionPlanRequest>, I>>(base?: I): GetTuitionPlanRequest {
    return GetTuitionPlanRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTuitionPlanRequest>, I>>(object: I): GetTuitionPlanRequest {
    const message = createBaseGetTuitionPlanRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.id = (object.id !== undefined && object.id !== null) ? ObjectId.fromPartial(object.id) : undefined;
    return message;
  },
};

function createBaseListTuitionPlansRequest(): ListTuitionPlansRequest {
  return { context: undefined, schoolYear: undefined, archived: false };
}

export const ListTuitionPlansRequest: MessageFns<ListTuitionPlansRequest> = {
  encode(message: ListTuitionPlansRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.schoolYear !== undefined) {
      ObjectId.encode(message.schoolYear, writer.uint32(18).fork()).join();
    }
    if (message.archived !== undefined && message.archived !== false) {
      writer.uint32(24).bool(message.archived);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTuitionPlansRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTuitionPlansRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.schoolYear = ObjectId.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.archived = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListTuitionPlansRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      schoolYear: isSet(object.schoolYear) ? ObjectId.fromJSON(object.schoolYear) : undefined,
      archived: isSet(object.archived) ? globalThis.Boolean(object.archived) : false,
    };
  },

  toJSON(message: ListTuitionPlansRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.schoolYear !== undefined) {
      obj.schoolYear = ObjectId.toJSON(message.schoolYear);
    }
    if (message.archived !== undefined && message.archived !== false) {
      obj.archived = message.archived;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListTuitionPlansRequest>, I>>(base?: I): ListTuitionPlansRequest {
    return ListTuitionPlansRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListTuitionPlansRequest>, I>>(object: I): ListTuitionPlansRequest {
    const message = createBaseListTuitionPlansRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.schoolYear = (object.schoolYear !== undefined && object.schoolYear !== null)
      ? ObjectId.fromPartial(object.schoolYear)
      : undefined;
    message.archived = object.archived ?? false;
    return message;
  },
};

function createBaseListTuitionPlansResponse(): ListTuitionPlansResponse {
  return { plans: [] };
}

export const ListTuitionPlansResponse: MessageFns<ListTuitionPlansResponse> = {
  encode(message: ListTuitionPlansResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.plans) {
      TuitionPlan.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTuitionPlansResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTuitionPlansResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.plans.push(TuitionPlan.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListTuitionPlansResponse {
    return {
      plans: globalThis.Array.isArray(object?.plans) ? object.plans.map((e: any) => TuitionPlan.fromJSON(e)) : [],
    };
  },

  toJSON(message: ListTuitionPlansResponse): unknown {
    const obj: any = {};
    if (message.plans?.length) {
      obj.plans = message.plans.map((e) => TuitionPlan.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListTuitionPlansResponse>, I>>(base?: I): ListTuitionPlansResponse {
    return ListTuitionPlansResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListTuitionPlansResponse>, I>>(object: I): ListTuitionPlansResponse {
    const message = createBaseListTuitionPlansResponse();
    message.plans = object.plans?.map((e) => TuitionPlan.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCreateTuitionPlanRequest(): CreateTuitionPlanRequest {
  return {
    context: undefined,
    schoolYear: undefined,
    name: "",
    description: "",
    scheduleType: PaymentScheduleType.ONE_TIME,
    numberOfMonths: 0,
    installments: [],
  };
}

export const CreateTuitionPlanRequest: MessageFns<CreateTuitionPlanRequest> = {
  encode(message: CreateTuitionPlanRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.schoolYear !== undefined) {
      ObjectId.encode(message.schoolYear, writer.uint32(18).fork()).join();
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(34).string(message.description);
    }
    if (message.scheduleType !== PaymentScheduleType.ONE_TIME) {
      writer.uint32(40).int32(paymentScheduleTypeToNumber(message.scheduleType));
    }
    if (message.numberOfMonths !== undefined && message.numberOfMonths !== 0) {
      writer.uint32(48).int32(message.numberOfMonths);
    }
    for (const v of message.installments) {
      PaymentInstallment.encode(v!, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateTuitionPlanRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTuitionPlanRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.schoolYear = ObjectId.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.scheduleType = paymentScheduleTypeFromJSON(reader.int32());
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.numberOfMonths = reader.int32();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.installments.push(PaymentInstallment.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateTuitionPlanRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      schoolYear: isSet(object.schoolYear) ? ObjectId.fromJSON(object.schoolYear) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      scheduleType: isSet(object.scheduleType)
        ? paymentScheduleTypeFromJSON(object.scheduleType)
        : PaymentScheduleType.ONE_TIME,
      numberOfMonths: isSet(object.numberOfMonths) ? globalThis.Number(object.numberOfMonths) : 0,
      installments: globalThis.Array.isArray(object?.installments)
        ? object.installments.map((e: any) => PaymentInstallment.fromJSON(e))
        : [],
    };
  },

  toJSON(message: CreateTuitionPlanRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.schoolYear !== undefined) {
      obj.schoolYear = ObjectId.toJSON(message.schoolYear);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.scheduleType !== PaymentScheduleType.ONE_TIME) {
      obj.scheduleType = paymentScheduleTypeToJSON(message.scheduleType);
    }
    if (message.numberOfMonths !== undefined && message.numberOfMonths !== 0) {
      obj.numberOfMonths = Math.round(message.numberOfMonths);
    }
    if (message.installments?.length) {
      obj.installments = message.installments.map((e) => PaymentInstallment.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateTuitionPlanRequest>, I>>(base?: I): CreateTuitionPlanRequest {
    return CreateTuitionPlanRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateTuitionPlanRequest>, I>>(object: I): CreateTuitionPlanRequest {
    const message = createBaseCreateTuitionPlanRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.schoolYear = (object.schoolYear !== undefined && object.schoolYear !== null)
      ? ObjectId.fromPartial(object.schoolYear)
      : undefined;
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.scheduleType = object.scheduleType ?? PaymentScheduleType.ONE_TIME;
    message.numberOfMonths = object.numberOfMonths ?? 0;
    message.installments = object.installments?.map((e) => PaymentInstallment.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUpdateTuitionPlanRequest(): UpdateTuitionPlanRequest {
  return {
    context: undefined,
    id: undefined,
    name: "",
    description: "",
    scheduleType: PaymentScheduleType.ONE_TIME,
    numberOfMonths: 0,
    installments: [],
  };
}

export const UpdateTuitionPlanRequest: MessageFns<UpdateTuitionPlanRequest> = {
  encode(message: UpdateTuitionPlanRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.id !== undefined) {
      ObjectId.encode(message.id, writer.uint32(18).fork()).join();
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(34).string(message.description);
    }
    if (message.scheduleType !== PaymentScheduleType.ONE_TIME) {
      writer.uint32(40).int32(paymentScheduleTypeToNumber(message.scheduleType));
    }
    if (message.numberOfMonths !== undefined && message.numberOfMonths !== 0) {
      writer.uint32(48).int32(message.numberOfMonths);
    }
    for (const v of message.installments) {
      PaymentInstallment.encode(v!, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateTuitionPlanRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateTuitionPlanRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.scheduleType = paymentScheduleTypeFromJSON(reader.int32());
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.numberOfMonths = reader.int32();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.installments.push(PaymentInstallment.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateTuitionPlanRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      id: isSet(object.id) ? ObjectId.fromJSON(object.id) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      scheduleType: isSet(object.scheduleType)
        ? paymentScheduleTypeFromJSON(object.scheduleType)
        : PaymentScheduleType.ONE_TIME,
      numberOfMonths: isSet(object.numberOfMonths) ? globalThis.Number(object.numberOfMonths) : 0,
      installments: globalThis.Array.isArray(object?.installments)
        ? object.installments.map((e: any) => PaymentInstallment.fromJSON(e))
        : [],
    };
  },

  toJSON(message: UpdateTuitionPlanRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.id !== undefined) {
      obj.id = ObjectId.toJSON(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.scheduleType !== PaymentScheduleType.ONE_TIME) {
      obj.scheduleType = paymentScheduleTypeToJSON(message.scheduleType);
    }
    if (message.numberOfMonths !== undefined && message.numberOfMonths !== 0) {
      obj.numberOfMonths = Math.round(message.numberOfMonths);
    }
    if (message.installments?.length) {
      obj.installments = message.installments.map((e) => PaymentInstallment.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateTuitionPlanRequest>, I>>(base?: I): UpdateTuitionPlanRequest {
    return UpdateTuitionPlanRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateTuitionPlanRequest>, I>>(object: I): UpdateTuitionPlanRequest {
    const message = createBaseUpdateTuitionPlanRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.id = (object.id !== undefined && object.id !== null) ? ObjectId.fromPartial(object.id) : undefined;
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.scheduleType = object.scheduleType ?? PaymentScheduleType.ONE_TIME;
    message.numberOfMonths = object.numberOfMonths ?? 0;
    message.installments = object.installments?.map((e) => PaymentInstallment.fromPartial(e)) || [];
    return message;
  },
};

function createBaseArchiveTuitionPlanRequest(): ArchiveTuitionPlanRequest {
  return { context: undefined, id: undefined };
}

export const ArchiveTuitionPlanRequest: MessageFns<ArchiveTuitionPlanRequest> = {
  encode(message: ArchiveTuitionPlanRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.id !== undefined) {
      ObjectId.encode(message.id, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArchiveTuitionPlanRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArchiveTuitionPlanRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.id = ObjectId.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArchiveTuitionPlanRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      id: isSet(object.id) ? ObjectId.fromJSON(object.id) : undefined,
    };
  },

  toJSON(message: ArchiveTuitionPlanRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.id !== undefined) {
      obj.id = ObjectId.toJSON(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArchiveTuitionPlanRequest>, I>>(base?: I): ArchiveTuitionPlanRequest {
    return ArchiveTuitionPlanRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArchiveTuitionPlanRequest>, I>>(object: I): ArchiveTuitionPlanRequest {
    const message = createBaseArchiveTuitionPlanRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.id = (object.id !== undefined && object.id !== null) ? ObjectId.fromPartial(object.id) : undefined;
    return message;
  },
};

function createBaseUnarchiveTuitionPlanRequest(): UnarchiveTuitionPlanRequest {
  return { context: undefined, id: undefined };
}

export const UnarchiveTuitionPlanRequest: MessageFns<UnarchiveTuitionPlanRequest> = {
  encode(message: UnarchiveTuitionPlanRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.id !== undefined) {
      ObjectId.encode(message.id, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UnarchiveTuitionPlanRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUnarchiveTuitionPlanRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.id = ObjectId.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UnarchiveTuitionPlanRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      id: isSet(object.id) ? ObjectId.fromJSON(object.id) : undefined,
    };
  },

  toJSON(message: UnarchiveTuitionPlanRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.id !== undefined) {
      obj.id = ObjectId.toJSON(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UnarchiveTuitionPlanRequest>, I>>(base?: I): UnarchiveTuitionPlanRequest {
    return UnarchiveTuitionPlanRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UnarchiveTuitionPlanRequest>, I>>(object: I): UnarchiveTuitionPlanRequest {
    const message = createBaseUnarchiveTuitionPlanRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.id = (object.id !== undefined && object.id !== null) ? ObjectId.fromPartial(object.id) : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
