// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: utils/request_context.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { UserRole, userRoleFromJSON, userRoleToJSON, userRoleToNumber } from "../user_service/user_role";
import { ObjectId } from "./object_id";
import { UserType, userTypeFromJSON, userTypeToJSON, userTypeToNumber } from "./user_type";

export const protobufPackage = "utils";

export enum ServiceContext {
  AutoPaymentScheduling = "AutoPaymentScheduling",
  AutoPaymentConsumer = "AutoPaymentConsumer",
  OrganizationInvoices = "OrganizationInvoices",
  StagingDataSyncJob = "StagingDataSyncJob",
  NotificationService = "NotificationService",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function serviceContextFromJSON(object: any): ServiceContext {
  switch (object) {
    case 1:
    case "AutoPaymentScheduling":
      return ServiceContext.AutoPaymentScheduling;
    case 2:
    case "AutoPaymentConsumer":
      return ServiceContext.AutoPaymentConsumer;
    case 3:
    case "OrganizationInvoices":
      return ServiceContext.OrganizationInvoices;
    case 4:
    case "StagingDataSyncJob":
      return ServiceContext.StagingDataSyncJob;
    case 5:
    case "NotificationService":
      return ServiceContext.NotificationService;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ServiceContext.UNRECOGNIZED;
  }
}

export function serviceContextToJSON(object: ServiceContext): string {
  switch (object) {
    case ServiceContext.AutoPaymentScheduling:
      return "AutoPaymentScheduling";
    case ServiceContext.AutoPaymentConsumer:
      return "AutoPaymentConsumer";
    case ServiceContext.OrganizationInvoices:
      return "OrganizationInvoices";
    case ServiceContext.StagingDataSyncJob:
      return "StagingDataSyncJob";
    case ServiceContext.NotificationService:
      return "NotificationService";
    case ServiceContext.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function serviceContextToNumber(object: ServiceContext): number {
  switch (object) {
    case ServiceContext.AutoPaymentScheduling:
      return 1;
    case ServiceContext.AutoPaymentConsumer:
      return 2;
    case ServiceContext.OrganizationInvoices:
      return 3;
    case ServiceContext.StagingDataSyncJob:
      return 4;
    case ServiceContext.NotificationService:
      return 5;
    case ServiceContext.UNRECOGNIZED:
    default:
      return -1;
  }
}

export interface RequestContext {
  user_context: UserContext | undefined;
  is_testing?: boolean | undefined;
  service_based_context_name?: ServiceContext | undefined;
}

export interface UserContext {
  user_id: ObjectId | undefined;
  user_type?: UserType | undefined;
  user_auth_token?: string | undefined;
  organization_id?: ObjectId | undefined;
  roles: UserRole[];
  parent_family_ids: ObjectId[];
  parent_student_ids: ObjectId[];
  full_name?: string | undefined;
  firebase_token?: string | undefined;
  exp?: number | undefined;
  trace_id?: string | undefined;
}

function createBaseRequestContext(): RequestContext {
  return { user_context: undefined, is_testing: undefined, service_based_context_name: undefined };
}

export const RequestContext: MessageFns<RequestContext> = {
  encode(message: RequestContext, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_context !== undefined) {
      UserContext.encode(message.user_context, writer.uint32(10).fork()).join();
    }
    if (message.is_testing !== undefined) {
      writer.uint32(16).bool(message.is_testing);
    }
    if (message.service_based_context_name !== undefined) {
      writer.uint32(24).int32(serviceContextToNumber(message.service_based_context_name));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestContext {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestContext();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.user_context = UserContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.is_testing = reader.bool();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.service_based_context_name = serviceContextFromJSON(reader.int32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestContext {
    return {
      user_context: isSet(object.userContext) ? UserContext.fromJSON(object.userContext) : undefined,
      is_testing: isSet(object.isTesting) ? globalThis.Boolean(object.isTesting) : undefined,
      service_based_context_name: isSet(object.serviceBasedContextName)
        ? serviceContextFromJSON(object.serviceBasedContextName)
        : undefined,
    };
  },

  toJSON(message: RequestContext): unknown {
    const obj: any = {};
    if (message.user_context !== undefined) {
      obj.userContext = UserContext.toJSON(message.user_context);
    }
    if (message.is_testing !== undefined) {
      obj.isTesting = message.is_testing;
    }
    if (message.service_based_context_name !== undefined) {
      obj.serviceBasedContextName = serviceContextToJSON(message.service_based_context_name);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestContext>, I>>(base?: I): RequestContext {
    return RequestContext.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestContext>, I>>(object: I): RequestContext {
    const message = createBaseRequestContext();
    message.user_context = (object.user_context !== undefined && object.user_context !== null)
      ? UserContext.fromPartial(object.user_context)
      : undefined;
    message.is_testing = object.is_testing ?? undefined;
    message.service_based_context_name = object.service_based_context_name ?? undefined;
    return message;
  },
};

function createBaseUserContext(): UserContext {
  return {
    user_id: undefined,
    user_type: undefined,
    user_auth_token: undefined,
    organization_id: undefined,
    roles: [],
    parent_family_ids: [],
    parent_student_ids: [],
    full_name: undefined,
    firebase_token: undefined,
    exp: undefined,
    trace_id: undefined,
  };
}

export const UserContext: MessageFns<UserContext> = {
  encode(message: UserContext, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== undefined) {
      ObjectId.encode(message.user_id, writer.uint32(10).fork()).join();
    }
    if (message.user_type !== undefined) {
      writer.uint32(16).int32(userTypeToNumber(message.user_type));
    }
    if (message.user_auth_token !== undefined) {
      writer.uint32(26).string(message.user_auth_token);
    }
    if (message.organization_id !== undefined) {
      ObjectId.encode(message.organization_id, writer.uint32(34).fork()).join();
    }
    writer.uint32(42).fork();
    for (const v of message.roles) {
      writer.int32(userRoleToNumber(v));
    }
    writer.join();
    for (const v of message.parent_family_ids) {
      ObjectId.encode(v!, writer.uint32(50).fork()).join();
    }
    for (const v of message.parent_student_ids) {
      ObjectId.encode(v!, writer.uint32(58).fork()).join();
    }
    if (message.full_name !== undefined) {
      writer.uint32(66).string(message.full_name);
    }
    if (message.firebase_token !== undefined) {
      writer.uint32(74).string(message.firebase_token);
    }
    if (message.exp !== undefined) {
      writer.uint32(80).uint64(message.exp);
    }
    if (message.trace_id !== undefined) {
      writer.uint32(90).string(message.trace_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserContext {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserContext();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.user_id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.user_type = userTypeFromJSON(reader.int32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.user_auth_token = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.organization_id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag === 40) {
            message.roles.push(userRoleFromJSON(reader.int32()));

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.roles.push(userRoleFromJSON(reader.int32()));
            }

            continue;
          }

          break;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.parent_family_ids.push(ObjectId.decode(reader, reader.uint32()));
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.parent_student_ids.push(ObjectId.decode(reader, reader.uint32()));
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.full_name = reader.string();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.firebase_token = reader.string();
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.exp = longToNumber(reader.uint64());
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.trace_id = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserContext {
    return {
      user_id: isSet(object.userId) ? ObjectId.fromJSON(object.userId) : undefined,
      user_type: isSet(object.userType) ? userTypeFromJSON(object.userType) : undefined,
      user_auth_token: isSet(object.userAuthToken) ? globalThis.String(object.userAuthToken) : undefined,
      organization_id: isSet(object.organizationId) ? ObjectId.fromJSON(object.organizationId) : undefined,
      roles: globalThis.Array.isArray(object?.roles) ? object.roles.map((e: any) => userRoleFromJSON(e)) : [],
      parent_family_ids: globalThis.Array.isArray(object?.parentFamilyIds)
        ? object.parentFamilyIds.map((e: any) => ObjectId.fromJSON(e))
        : [],
      parent_student_ids: globalThis.Array.isArray(object?.parentStudentIds)
        ? object.parentStudentIds.map((e: any) => ObjectId.fromJSON(e))
        : [],
      full_name: isSet(object.fullName) ? globalThis.String(object.fullName) : undefined,
      firebase_token: isSet(object.firebaseToken) ? globalThis.String(object.firebaseToken) : undefined,
      exp: isSet(object.exp) ? globalThis.Number(object.exp) : undefined,
      trace_id: isSet(object.traceId) ? globalThis.String(object.traceId) : undefined,
    };
  },

  toJSON(message: UserContext): unknown {
    const obj: any = {};
    if (message.user_id !== undefined) {
      obj.userId = ObjectId.toJSON(message.user_id);
    }
    if (message.user_type !== undefined) {
      obj.userType = userTypeToJSON(message.user_type);
    }
    if (message.user_auth_token !== undefined) {
      obj.userAuthToken = message.user_auth_token;
    }
    if (message.organization_id !== undefined) {
      obj.organizationId = ObjectId.toJSON(message.organization_id);
    }
    if (message.roles?.length) {
      obj.roles = message.roles.map((e) => userRoleToJSON(e));
    }
    if (message.parent_family_ids?.length) {
      obj.parentFamilyIds = message.parent_family_ids.map((e) => ObjectId.toJSON(e));
    }
    if (message.parent_student_ids?.length) {
      obj.parentStudentIds = message.parent_student_ids.map((e) => ObjectId.toJSON(e));
    }
    if (message.full_name !== undefined) {
      obj.fullName = message.full_name;
    }
    if (message.firebase_token !== undefined) {
      obj.firebaseToken = message.firebase_token;
    }
    if (message.exp !== undefined) {
      obj.exp = Math.round(message.exp);
    }
    if (message.trace_id !== undefined) {
      obj.traceId = message.trace_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserContext>, I>>(base?: I): UserContext {
    return UserContext.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserContext>, I>>(object: I): UserContext {
    const message = createBaseUserContext();
    message.user_id = (object.user_id !== undefined && object.user_id !== null)
      ? ObjectId.fromPartial(object.user_id)
      : undefined;
    message.user_type = object.user_type ?? undefined;
    message.user_auth_token = object.user_auth_token ?? undefined;
    message.organization_id = (object.organization_id !== undefined && object.organization_id !== null)
      ? ObjectId.fromPartial(object.organization_id)
      : undefined;
    message.roles = object.roles?.map((e) => e) || [];
    message.parent_family_ids = object.parent_family_ids?.map((e) => ObjectId.fromPartial(e)) || [];
    message.parent_student_ids = object.parent_student_ids?.map((e) => ObjectId.fromPartial(e)) || [];
    message.full_name = object.full_name ?? undefined;
    message.firebase_token = object.firebase_token ?? undefined;
    message.exp = object.exp ?? undefined;
    message.trace_id = object.trace_id ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
