// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: class_service/ai_interaction_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ObjectId } from "../utils/object_id";
import { RequestContext } from "../utils/request_context";
import {
  AiInteractionRecord,
  AiInteractionRecordStatus,
  aiInteractionRecordStatusFromJSON,
  aiInteractionRecordStatusToJSON,
  aiInteractionRecordStatusToNumber,
} from "./ai_interaction_record";

export const protobufPackage = "class_service.ai_interaction_service";

export interface GetAiInteractionRecordRequest {
  context: RequestContext | undefined;
  ai_interaction_record_id: ObjectId | undefined;
}

export interface GetAiInteractionRecordResponse {
  ai_interaction_record: AiInteractionRecord | undefined;
}

export interface ListAiInteractionRecordsRequest {
  context: RequestContext | undefined;
  per_page?: number | undefined;
  page?:
    | number
    | undefined;
  /** Searches in response field */
  name_search?: string | undefined;
}

export interface ListAiInteractionRecordsResponse {
  ai_interaction_record: AiInteractionRecord[];
  ai_interaction_record_count: number;
}

export interface PreprocessingRequest {
  context: RequestContext | undefined;
  prompt: string;
}

export interface PreprocessingResponse {
  ai_interaction_record: AiInteractionRecord | undefined;
}

export interface PostprocessingRequest {
  context: RequestContext | undefined;
  ai_interaction_record_id: ObjectId | undefined;
  response: string;
  status: AiInteractionRecordStatus;
}

export interface PostprocessingResponse {
  ai_interaction_record: AiInteractionRecord | undefined;
}

function createBaseGetAiInteractionRecordRequest(): GetAiInteractionRecordRequest {
  return { context: undefined, ai_interaction_record_id: undefined };
}

export const GetAiInteractionRecordRequest: MessageFns<GetAiInteractionRecordRequest> = {
  encode(message: GetAiInteractionRecordRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.ai_interaction_record_id !== undefined) {
      ObjectId.encode(message.ai_interaction_record_id, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAiInteractionRecordRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAiInteractionRecordRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.ai_interaction_record_id = ObjectId.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAiInteractionRecordRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      ai_interaction_record_id: isSet(object.aiInteractionRecordId)
        ? ObjectId.fromJSON(object.aiInteractionRecordId)
        : undefined,
    };
  },

  toJSON(message: GetAiInteractionRecordRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.ai_interaction_record_id !== undefined) {
      obj.aiInteractionRecordId = ObjectId.toJSON(message.ai_interaction_record_id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAiInteractionRecordRequest>, I>>(base?: I): GetAiInteractionRecordRequest {
    return GetAiInteractionRecordRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAiInteractionRecordRequest>, I>>(
    object: I,
  ): GetAiInteractionRecordRequest {
    const message = createBaseGetAiInteractionRecordRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.ai_interaction_record_id =
      (object.ai_interaction_record_id !== undefined && object.ai_interaction_record_id !== null)
        ? ObjectId.fromPartial(object.ai_interaction_record_id)
        : undefined;
    return message;
  },
};

function createBaseGetAiInteractionRecordResponse(): GetAiInteractionRecordResponse {
  return { ai_interaction_record: undefined };
}

export const GetAiInteractionRecordResponse: MessageFns<GetAiInteractionRecordResponse> = {
  encode(message: GetAiInteractionRecordResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ai_interaction_record !== undefined) {
      AiInteractionRecord.encode(message.ai_interaction_record, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAiInteractionRecordResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAiInteractionRecordResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ai_interaction_record = AiInteractionRecord.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAiInteractionRecordResponse {
    return {
      ai_interaction_record: isSet(object.aiInteractionRecord)
        ? AiInteractionRecord.fromJSON(object.aiInteractionRecord)
        : undefined,
    };
  },

  toJSON(message: GetAiInteractionRecordResponse): unknown {
    const obj: any = {};
    if (message.ai_interaction_record !== undefined) {
      obj.aiInteractionRecord = AiInteractionRecord.toJSON(message.ai_interaction_record);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAiInteractionRecordResponse>, I>>(base?: I): GetAiInteractionRecordResponse {
    return GetAiInteractionRecordResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAiInteractionRecordResponse>, I>>(
    object: I,
  ): GetAiInteractionRecordResponse {
    const message = createBaseGetAiInteractionRecordResponse();
    message.ai_interaction_record =
      (object.ai_interaction_record !== undefined && object.ai_interaction_record !== null)
        ? AiInteractionRecord.fromPartial(object.ai_interaction_record)
        : undefined;
    return message;
  },
};

function createBaseListAiInteractionRecordsRequest(): ListAiInteractionRecordsRequest {
  return { context: undefined, per_page: 0, page: 0, name_search: "" };
}

export const ListAiInteractionRecordsRequest: MessageFns<ListAiInteractionRecordsRequest> = {
  encode(message: ListAiInteractionRecordsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.per_page !== undefined && message.per_page !== 0) {
      writer.uint32(16).uint64(message.per_page);
    }
    if (message.page !== undefined && message.page !== 0) {
      writer.uint32(24).uint64(message.page);
    }
    if (message.name_search !== undefined && message.name_search !== "") {
      writer.uint32(34).string(message.name_search);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListAiInteractionRecordsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAiInteractionRecordsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.per_page = longToNumber(reader.uint64());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.page = longToNumber(reader.uint64());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.name_search = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListAiInteractionRecordsRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      per_page: isSet(object.perPage) ? globalThis.Number(object.perPage) : 0,
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      name_search: isSet(object.nameSearch) ? globalThis.String(object.nameSearch) : "",
    };
  },

  toJSON(message: ListAiInteractionRecordsRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.per_page !== undefined && message.per_page !== 0) {
      obj.perPage = Math.round(message.per_page);
    }
    if (message.page !== undefined && message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.name_search !== undefined && message.name_search !== "") {
      obj.nameSearch = message.name_search;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListAiInteractionRecordsRequest>, I>>(base?: I): ListAiInteractionRecordsRequest {
    return ListAiInteractionRecordsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListAiInteractionRecordsRequest>, I>>(
    object: I,
  ): ListAiInteractionRecordsRequest {
    const message = createBaseListAiInteractionRecordsRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.per_page = object.per_page ?? 0;
    message.page = object.page ?? 0;
    message.name_search = object.name_search ?? "";
    return message;
  },
};

function createBaseListAiInteractionRecordsResponse(): ListAiInteractionRecordsResponse {
  return { ai_interaction_record: [], ai_interaction_record_count: 0 };
}

export const ListAiInteractionRecordsResponse: MessageFns<ListAiInteractionRecordsResponse> = {
  encode(message: ListAiInteractionRecordsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.ai_interaction_record) {
      AiInteractionRecord.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.ai_interaction_record_count !== 0) {
      writer.uint32(16).uint64(message.ai_interaction_record_count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListAiInteractionRecordsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAiInteractionRecordsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ai_interaction_record.push(AiInteractionRecord.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.ai_interaction_record_count = longToNumber(reader.uint64());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListAiInteractionRecordsResponse {
    return {
      ai_interaction_record: globalThis.Array.isArray(object?.aiInteractionRecord)
        ? object.aiInteractionRecord.map((e: any) => AiInteractionRecord.fromJSON(e))
        : [],
      ai_interaction_record_count: isSet(object.aiInteractionRecordCount)
        ? globalThis.Number(object.aiInteractionRecordCount)
        : 0,
    };
  },

  toJSON(message: ListAiInteractionRecordsResponse): unknown {
    const obj: any = {};
    if (message.ai_interaction_record?.length) {
      obj.aiInteractionRecord = message.ai_interaction_record.map((e) => AiInteractionRecord.toJSON(e));
    }
    if (message.ai_interaction_record_count !== 0) {
      obj.aiInteractionRecordCount = Math.round(message.ai_interaction_record_count);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListAiInteractionRecordsResponse>, I>>(
    base?: I,
  ): ListAiInteractionRecordsResponse {
    return ListAiInteractionRecordsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListAiInteractionRecordsResponse>, I>>(
    object: I,
  ): ListAiInteractionRecordsResponse {
    const message = createBaseListAiInteractionRecordsResponse();
    message.ai_interaction_record = object.ai_interaction_record?.map((e) => AiInteractionRecord.fromPartial(e)) || [];
    message.ai_interaction_record_count = object.ai_interaction_record_count ?? 0;
    return message;
  },
};

function createBasePreprocessingRequest(): PreprocessingRequest {
  return { context: undefined, prompt: "" };
}

export const PreprocessingRequest: MessageFns<PreprocessingRequest> = {
  encode(message: PreprocessingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.prompt !== "") {
      writer.uint32(18).string(message.prompt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PreprocessingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePreprocessingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.prompt = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PreprocessingRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      prompt: isSet(object.prompt) ? globalThis.String(object.prompt) : "",
    };
  },

  toJSON(message: PreprocessingRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.prompt !== "") {
      obj.prompt = message.prompt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PreprocessingRequest>, I>>(base?: I): PreprocessingRequest {
    return PreprocessingRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PreprocessingRequest>, I>>(object: I): PreprocessingRequest {
    const message = createBasePreprocessingRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.prompt = object.prompt ?? "";
    return message;
  },
};

function createBasePreprocessingResponse(): PreprocessingResponse {
  return { ai_interaction_record: undefined };
}

export const PreprocessingResponse: MessageFns<PreprocessingResponse> = {
  encode(message: PreprocessingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ai_interaction_record !== undefined) {
      AiInteractionRecord.encode(message.ai_interaction_record, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PreprocessingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePreprocessingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ai_interaction_record = AiInteractionRecord.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PreprocessingResponse {
    return {
      ai_interaction_record: isSet(object.aiInteractionRecord)
        ? AiInteractionRecord.fromJSON(object.aiInteractionRecord)
        : undefined,
    };
  },

  toJSON(message: PreprocessingResponse): unknown {
    const obj: any = {};
    if (message.ai_interaction_record !== undefined) {
      obj.aiInteractionRecord = AiInteractionRecord.toJSON(message.ai_interaction_record);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PreprocessingResponse>, I>>(base?: I): PreprocessingResponse {
    return PreprocessingResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PreprocessingResponse>, I>>(object: I): PreprocessingResponse {
    const message = createBasePreprocessingResponse();
    message.ai_interaction_record =
      (object.ai_interaction_record !== undefined && object.ai_interaction_record !== null)
        ? AiInteractionRecord.fromPartial(object.ai_interaction_record)
        : undefined;
    return message;
  },
};

function createBasePostprocessingRequest(): PostprocessingRequest {
  return {
    context: undefined,
    ai_interaction_record_id: undefined,
    response: "",
    status: AiInteractionRecordStatus.Pending,
  };
}

export const PostprocessingRequest: MessageFns<PostprocessingRequest> = {
  encode(message: PostprocessingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.ai_interaction_record_id !== undefined) {
      ObjectId.encode(message.ai_interaction_record_id, writer.uint32(18).fork()).join();
    }
    if (message.response !== "") {
      writer.uint32(26).string(message.response);
    }
    if (message.status !== AiInteractionRecordStatus.Pending) {
      writer.uint32(32).int32(aiInteractionRecordStatusToNumber(message.status));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PostprocessingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePostprocessingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.ai_interaction_record_id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.response = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.status = aiInteractionRecordStatusFromJSON(reader.int32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PostprocessingRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      ai_interaction_record_id: isSet(object.aiInteractionRecordId)
        ? ObjectId.fromJSON(object.aiInteractionRecordId)
        : undefined,
      response: isSet(object.response) ? globalThis.String(object.response) : "",
      status: isSet(object.status)
        ? aiInteractionRecordStatusFromJSON(object.status)
        : AiInteractionRecordStatus.Pending,
    };
  },

  toJSON(message: PostprocessingRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.ai_interaction_record_id !== undefined) {
      obj.aiInteractionRecordId = ObjectId.toJSON(message.ai_interaction_record_id);
    }
    if (message.response !== "") {
      obj.response = message.response;
    }
    if (message.status !== AiInteractionRecordStatus.Pending) {
      obj.status = aiInteractionRecordStatusToJSON(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PostprocessingRequest>, I>>(base?: I): PostprocessingRequest {
    return PostprocessingRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PostprocessingRequest>, I>>(object: I): PostprocessingRequest {
    const message = createBasePostprocessingRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.ai_interaction_record_id =
      (object.ai_interaction_record_id !== undefined && object.ai_interaction_record_id !== null)
        ? ObjectId.fromPartial(object.ai_interaction_record_id)
        : undefined;
    message.response = object.response ?? "";
    message.status = object.status ?? AiInteractionRecordStatus.Pending;
    return message;
  },
};

function createBasePostprocessingResponse(): PostprocessingResponse {
  return { ai_interaction_record: undefined };
}

export const PostprocessingResponse: MessageFns<PostprocessingResponse> = {
  encode(message: PostprocessingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ai_interaction_record !== undefined) {
      AiInteractionRecord.encode(message.ai_interaction_record, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PostprocessingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePostprocessingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ai_interaction_record = AiInteractionRecord.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PostprocessingResponse {
    return {
      ai_interaction_record: isSet(object.aiInteractionRecord)
        ? AiInteractionRecord.fromJSON(object.aiInteractionRecord)
        : undefined,
    };
  },

  toJSON(message: PostprocessingResponse): unknown {
    const obj: any = {};
    if (message.ai_interaction_record !== undefined) {
      obj.aiInteractionRecord = AiInteractionRecord.toJSON(message.ai_interaction_record);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PostprocessingResponse>, I>>(base?: I): PostprocessingResponse {
    return PostprocessingResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PostprocessingResponse>, I>>(object: I): PostprocessingResponse {
    const message = createBasePostprocessingResponse();
    message.ai_interaction_record =
      (object.ai_interaction_record !== undefined && object.ai_interaction_record !== null)
        ? AiInteractionRecord.fromPartial(object.ai_interaction_record)
        : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
