// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: class_service/transcript_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { StudentGrade, studentGradeFromJSON, studentGradeToJSON, studentGradeToNumber } from "../user_service/student";
import { ObjectId } from "../utils/object_id";
import { RequestContext } from "../utils/request_context";

export const protobufPackage = "class_service.transcript_service";

export interface GetStudentTranscriptRequest {
  context: RequestContext | undefined;
  student_id: ObjectId | undefined;
}

export interface TranscriptPrimaryIdField {
  field_name?: string | undefined;
  value?: string | undefined;
}

export interface TranscriptHeader {
  student_name?: string | undefined;
  primary_id_field?: TranscriptPrimaryIdField | undefined;
  gender?: string | undefined;
  date_of_birth?: string | undefined;
  school_name?: string | undefined;
  date_of_issue?: string | undefined;
}

export interface TranscriptRow {
  year?: number | undefined;
  month?: number | undefined;
  grade?: StudentGrade | undefined;
  course_title?: string | undefined;
  course_code?: string | undefined;
  percentage_grade?: string | undefined;
  credit?: number | undefined;
  compulsory?: boolean | undefined;
  note?: string | undefined;
  credit_earned?: boolean | undefined;
}

export interface CategoryProgress {
  category_id: ObjectId | undefined;
  category_name?: string | undefined;
  credits_required?: number | undefined;
  credits_earned?: number | undefined;
}

export interface TranscriptSummary {
  total_credits_earned?: number | undefined;
  compulsory_credits_earned?: number | undefined;
  optional_credits_earned?: number | undefined;
  category_progress: CategoryProgress[];
}

export interface TranscriptDiagnostic {
  course_id: ObjectId | undefined;
  course_name?: string | undefined;
  reason?: string | undefined;
}

export interface GetStudentTranscriptResponse {
  header: TranscriptHeader | undefined;
  rows: TranscriptRow[];
  summary: TranscriptSummary | undefined;
  diagnostics: TranscriptDiagnostic[];
}

export interface GetStudentDiplomaRequirementsRequest {
  context: RequestContext | undefined;
  student_id: ObjectId | undefined;
}

export interface DiplomaRequirementRow {
  label?: string | undefined;
  is_group?: boolean | undefined;
  group_sub_labels: string[];
  total_required?: number | undefined;
  earned_this_year?: number | undefined;
  earned_to_date?: number | undefined;
}

export interface StudentGraduationTracking {
  id: ObjectId | undefined;
  student_id: ObjectId | undefined;
  community_involvement_hours_earned?: number | undefined;
  literacy_requirement_completed?: boolean | undefined;
  specialist_high_skills_major?: string | undefined;
  online_learning_credits_earned?: number | undefined;
  for_school_use_note?: string | undefined;
}

export interface GetStudentDiplomaRequirementsResponse {
  header: TranscriptHeader | undefined;
  compulsory_rows: DiplomaRequirementRow[];
  compulsory_total_required?: number | undefined;
  compulsory_earned_this_year?: number | undefined;
  compulsory_earned_to_date?: number | undefined;
  optional_total_required?: number | undefined;
  optional_earned_this_year?: number | undefined;
  optional_earned_to_date?: number | undefined;
  total_required?: number | undefined;
  total_earned_this_year?: number | undefined;
  total_earned_to_date?: number | undefined;
  community_involvement_hours_required?: number | undefined;
  community_involvement_hours_earned?: number | undefined;
  online_learning_credits_required?: number | undefined;
  online_learning_credits_earned?: number | undefined;
  literacy_requirement_completed?: boolean | undefined;
  specialist_high_skills_major?: string | undefined;
  for_school_use_note?: string | undefined;
  diagnostics: TranscriptDiagnostic[];
}

export interface UpsertStudentGraduationTrackingRequest {
  context: RequestContext | undefined;
  student_id: ObjectId | undefined;
  community_involvement_hours_earned?: number | undefined;
  literacy_requirement_completed?: boolean | undefined;
  specialist_high_skills_major?: string | undefined;
  online_learning_credits_earned?: number | undefined;
  for_school_use_note?: string | undefined;
}

function createBaseGetStudentTranscriptRequest(): GetStudentTranscriptRequest {
  return { context: undefined, student_id: undefined };
}

export const GetStudentTranscriptRequest: MessageFns<GetStudentTranscriptRequest> = {
  encode(message: GetStudentTranscriptRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.student_id !== undefined) {
      ObjectId.encode(message.student_id, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStudentTranscriptRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStudentTranscriptRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.student_id = ObjectId.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetStudentTranscriptRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      student_id: isSet(object.studentId) ? ObjectId.fromJSON(object.studentId) : undefined,
    };
  },

  toJSON(message: GetStudentTranscriptRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.student_id !== undefined) {
      obj.studentId = ObjectId.toJSON(message.student_id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStudentTranscriptRequest>, I>>(base?: I): GetStudentTranscriptRequest {
    return GetStudentTranscriptRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStudentTranscriptRequest>, I>>(object: I): GetStudentTranscriptRequest {
    const message = createBaseGetStudentTranscriptRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.student_id = (object.student_id !== undefined && object.student_id !== null)
      ? ObjectId.fromPartial(object.student_id)
      : undefined;
    return message;
  },
};

function createBaseTranscriptPrimaryIdField(): TranscriptPrimaryIdField {
  return { field_name: undefined, value: undefined };
}

export const TranscriptPrimaryIdField: MessageFns<TranscriptPrimaryIdField> = {
  encode(message: TranscriptPrimaryIdField, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.field_name !== undefined) {
      writer.uint32(10).string(message.field_name);
    }
    if (message.value !== undefined) {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TranscriptPrimaryIdField {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTranscriptPrimaryIdField();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.field_name = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TranscriptPrimaryIdField {
    return {
      field_name: isSet(object.fieldName) ? globalThis.String(object.fieldName) : undefined,
      value: isSet(object.value) ? globalThis.String(object.value) : undefined,
    };
  },

  toJSON(message: TranscriptPrimaryIdField): unknown {
    const obj: any = {};
    if (message.field_name !== undefined) {
      obj.fieldName = message.field_name;
    }
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TranscriptPrimaryIdField>, I>>(base?: I): TranscriptPrimaryIdField {
    return TranscriptPrimaryIdField.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TranscriptPrimaryIdField>, I>>(object: I): TranscriptPrimaryIdField {
    const message = createBaseTranscriptPrimaryIdField();
    message.field_name = object.field_name ?? undefined;
    message.value = object.value ?? undefined;
    return message;
  },
};

function createBaseTranscriptHeader(): TranscriptHeader {
  return {
    student_name: undefined,
    primary_id_field: undefined,
    gender: undefined,
    date_of_birth: undefined,
    school_name: undefined,
    date_of_issue: undefined,
  };
}

export const TranscriptHeader: MessageFns<TranscriptHeader> = {
  encode(message: TranscriptHeader, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.student_name !== undefined) {
      writer.uint32(10).string(message.student_name);
    }
    if (message.primary_id_field !== undefined) {
      TranscriptPrimaryIdField.encode(message.primary_id_field, writer.uint32(18).fork()).join();
    }
    if (message.gender !== undefined) {
      writer.uint32(26).string(message.gender);
    }
    if (message.date_of_birth !== undefined) {
      writer.uint32(34).string(message.date_of_birth);
    }
    if (message.school_name !== undefined) {
      writer.uint32(42).string(message.school_name);
    }
    if (message.date_of_issue !== undefined) {
      writer.uint32(50).string(message.date_of_issue);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TranscriptHeader {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTranscriptHeader();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.student_name = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.primary_id_field = TranscriptPrimaryIdField.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.gender = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.date_of_birth = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.school_name = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.date_of_issue = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TranscriptHeader {
    return {
      student_name: isSet(object.studentName) ? globalThis.String(object.studentName) : undefined,
      primary_id_field: isSet(object.primaryIdField)
        ? TranscriptPrimaryIdField.fromJSON(object.primaryIdField)
        : undefined,
      gender: isSet(object.gender) ? globalThis.String(object.gender) : undefined,
      date_of_birth: isSet(object.dateOfBirth) ? globalThis.String(object.dateOfBirth) : undefined,
      school_name: isSet(object.schoolName) ? globalThis.String(object.schoolName) : undefined,
      date_of_issue: isSet(object.dateOfIssue) ? globalThis.String(object.dateOfIssue) : undefined,
    };
  },

  toJSON(message: TranscriptHeader): unknown {
    const obj: any = {};
    if (message.student_name !== undefined) {
      obj.studentName = message.student_name;
    }
    if (message.primary_id_field !== undefined) {
      obj.primaryIdField = TranscriptPrimaryIdField.toJSON(message.primary_id_field);
    }
    if (message.gender !== undefined) {
      obj.gender = message.gender;
    }
    if (message.date_of_birth !== undefined) {
      obj.dateOfBirth = message.date_of_birth;
    }
    if (message.school_name !== undefined) {
      obj.schoolName = message.school_name;
    }
    if (message.date_of_issue !== undefined) {
      obj.dateOfIssue = message.date_of_issue;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TranscriptHeader>, I>>(base?: I): TranscriptHeader {
    return TranscriptHeader.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TranscriptHeader>, I>>(object: I): TranscriptHeader {
    const message = createBaseTranscriptHeader();
    message.student_name = object.student_name ?? undefined;
    message.primary_id_field = (object.primary_id_field !== undefined && object.primary_id_field !== null)
      ? TranscriptPrimaryIdField.fromPartial(object.primary_id_field)
      : undefined;
    message.gender = object.gender ?? undefined;
    message.date_of_birth = object.date_of_birth ?? undefined;
    message.school_name = object.school_name ?? undefined;
    message.date_of_issue = object.date_of_issue ?? undefined;
    return message;
  },
};

function createBaseTranscriptRow(): TranscriptRow {
  return {
    year: undefined,
    month: undefined,
    grade: undefined,
    course_title: undefined,
    course_code: undefined,
    percentage_grade: undefined,
    credit: undefined,
    compulsory: undefined,
    note: undefined,
    credit_earned: undefined,
  };
}

export const TranscriptRow: MessageFns<TranscriptRow> = {
  encode(message: TranscriptRow, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.year !== undefined) {
      writer.uint32(8).uint32(message.year);
    }
    if (message.month !== undefined) {
      writer.uint32(16).uint32(message.month);
    }
    if (message.grade !== undefined) {
      writer.uint32(24).int32(studentGradeToNumber(message.grade));
    }
    if (message.course_title !== undefined) {
      writer.uint32(34).string(message.course_title);
    }
    if (message.course_code !== undefined) {
      writer.uint32(42).string(message.course_code);
    }
    if (message.percentage_grade !== undefined) {
      writer.uint32(50).string(message.percentage_grade);
    }
    if (message.credit !== undefined) {
      writer.uint32(57).double(message.credit);
    }
    if (message.compulsory !== undefined) {
      writer.uint32(64).bool(message.compulsory);
    }
    if (message.note !== undefined) {
      writer.uint32(74).string(message.note);
    }
    if (message.credit_earned !== undefined) {
      writer.uint32(80).bool(message.credit_earned);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TranscriptRow {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTranscriptRow();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.year = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.month = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.grade = studentGradeFromJSON(reader.int32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.course_title = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.course_code = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.percentage_grade = reader.string();
          continue;
        case 7:
          if (tag !== 57) {
            break;
          }

          message.credit = reader.double();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.compulsory = reader.bool();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.note = reader.string();
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.credit_earned = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TranscriptRow {
    return {
      year: isSet(object.year) ? globalThis.Number(object.year) : undefined,
      month: isSet(object.month) ? globalThis.Number(object.month) : undefined,
      grade: isSet(object.grade) ? studentGradeFromJSON(object.grade) : undefined,
      course_title: isSet(object.courseTitle) ? globalThis.String(object.courseTitle) : undefined,
      course_code: isSet(object.courseCode) ? globalThis.String(object.courseCode) : undefined,
      percentage_grade: isSet(object.percentageGrade) ? globalThis.String(object.percentageGrade) : undefined,
      credit: isSet(object.credit) ? globalThis.Number(object.credit) : undefined,
      compulsory: isSet(object.compulsory) ? globalThis.Boolean(object.compulsory) : undefined,
      note: isSet(object.note) ? globalThis.String(object.note) : undefined,
      credit_earned: isSet(object.creditEarned) ? globalThis.Boolean(object.creditEarned) : undefined,
    };
  },

  toJSON(message: TranscriptRow): unknown {
    const obj: any = {};
    if (message.year !== undefined) {
      obj.year = Math.round(message.year);
    }
    if (message.month !== undefined) {
      obj.month = Math.round(message.month);
    }
    if (message.grade !== undefined) {
      obj.grade = studentGradeToJSON(message.grade);
    }
    if (message.course_title !== undefined) {
      obj.courseTitle = message.course_title;
    }
    if (message.course_code !== undefined) {
      obj.courseCode = message.course_code;
    }
    if (message.percentage_grade !== undefined) {
      obj.percentageGrade = message.percentage_grade;
    }
    if (message.credit !== undefined) {
      obj.credit = message.credit;
    }
    if (message.compulsory !== undefined) {
      obj.compulsory = message.compulsory;
    }
    if (message.note !== undefined) {
      obj.note = message.note;
    }
    if (message.credit_earned !== undefined) {
      obj.creditEarned = message.credit_earned;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TranscriptRow>, I>>(base?: I): TranscriptRow {
    return TranscriptRow.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TranscriptRow>, I>>(object: I): TranscriptRow {
    const message = createBaseTranscriptRow();
    message.year = object.year ?? undefined;
    message.month = object.month ?? undefined;
    message.grade = object.grade ?? undefined;
    message.course_title = object.course_title ?? undefined;
    message.course_code = object.course_code ?? undefined;
    message.percentage_grade = object.percentage_grade ?? undefined;
    message.credit = object.credit ?? undefined;
    message.compulsory = object.compulsory ?? undefined;
    message.note = object.note ?? undefined;
    message.credit_earned = object.credit_earned ?? undefined;
    return message;
  },
};

function createBaseCategoryProgress(): CategoryProgress {
  return { category_id: undefined, category_name: undefined, credits_required: undefined, credits_earned: undefined };
}

export const CategoryProgress: MessageFns<CategoryProgress> = {
  encode(message: CategoryProgress, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.category_id !== undefined) {
      ObjectId.encode(message.category_id, writer.uint32(10).fork()).join();
    }
    if (message.category_name !== undefined) {
      writer.uint32(18).string(message.category_name);
    }
    if (message.credits_required !== undefined) {
      writer.uint32(25).double(message.credits_required);
    }
    if (message.credits_earned !== undefined) {
      writer.uint32(33).double(message.credits_earned);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CategoryProgress {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCategoryProgress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.category_id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.category_name = reader.string();
          continue;
        case 3:
          if (tag !== 25) {
            break;
          }

          message.credits_required = reader.double();
          continue;
        case 4:
          if (tag !== 33) {
            break;
          }

          message.credits_earned = reader.double();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CategoryProgress {
    return {
      category_id: isSet(object.categoryId) ? ObjectId.fromJSON(object.categoryId) : undefined,
      category_name: isSet(object.categoryName) ? globalThis.String(object.categoryName) : undefined,
      credits_required: isSet(object.creditsRequired) ? globalThis.Number(object.creditsRequired) : undefined,
      credits_earned: isSet(object.creditsEarned) ? globalThis.Number(object.creditsEarned) : undefined,
    };
  },

  toJSON(message: CategoryProgress): unknown {
    const obj: any = {};
    if (message.category_id !== undefined) {
      obj.categoryId = ObjectId.toJSON(message.category_id);
    }
    if (message.category_name !== undefined) {
      obj.categoryName = message.category_name;
    }
    if (message.credits_required !== undefined) {
      obj.creditsRequired = message.credits_required;
    }
    if (message.credits_earned !== undefined) {
      obj.creditsEarned = message.credits_earned;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CategoryProgress>, I>>(base?: I): CategoryProgress {
    return CategoryProgress.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CategoryProgress>, I>>(object: I): CategoryProgress {
    const message = createBaseCategoryProgress();
    message.category_id = (object.category_id !== undefined && object.category_id !== null)
      ? ObjectId.fromPartial(object.category_id)
      : undefined;
    message.category_name = object.category_name ?? undefined;
    message.credits_required = object.credits_required ?? undefined;
    message.credits_earned = object.credits_earned ?? undefined;
    return message;
  },
};

function createBaseTranscriptSummary(): TranscriptSummary {
  return {
    total_credits_earned: undefined,
    compulsory_credits_earned: undefined,
    optional_credits_earned: undefined,
    category_progress: [],
  };
}

export const TranscriptSummary: MessageFns<TranscriptSummary> = {
  encode(message: TranscriptSummary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.total_credits_earned !== undefined) {
      writer.uint32(9).double(message.total_credits_earned);
    }
    if (message.compulsory_credits_earned !== undefined) {
      writer.uint32(17).double(message.compulsory_credits_earned);
    }
    if (message.optional_credits_earned !== undefined) {
      writer.uint32(25).double(message.optional_credits_earned);
    }
    for (const v of message.category_progress) {
      CategoryProgress.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TranscriptSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTranscriptSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 9) {
            break;
          }

          message.total_credits_earned = reader.double();
          continue;
        case 2:
          if (tag !== 17) {
            break;
          }

          message.compulsory_credits_earned = reader.double();
          continue;
        case 3:
          if (tag !== 25) {
            break;
          }

          message.optional_credits_earned = reader.double();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.category_progress.push(CategoryProgress.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TranscriptSummary {
    return {
      total_credits_earned: isSet(object.totalCreditsEarned) ? globalThis.Number(object.totalCreditsEarned) : undefined,
      compulsory_credits_earned: isSet(object.compulsoryCreditsEarned)
        ? globalThis.Number(object.compulsoryCreditsEarned)
        : undefined,
      optional_credits_earned: isSet(object.optionalCreditsEarned)
        ? globalThis.Number(object.optionalCreditsEarned)
        : undefined,
      category_progress: globalThis.Array.isArray(object?.categoryProgress)
        ? object.categoryProgress.map((e: any) => CategoryProgress.fromJSON(e))
        : [],
    };
  },

  toJSON(message: TranscriptSummary): unknown {
    const obj: any = {};
    if (message.total_credits_earned !== undefined) {
      obj.totalCreditsEarned = message.total_credits_earned;
    }
    if (message.compulsory_credits_earned !== undefined) {
      obj.compulsoryCreditsEarned = message.compulsory_credits_earned;
    }
    if (message.optional_credits_earned !== undefined) {
      obj.optionalCreditsEarned = message.optional_credits_earned;
    }
    if (message.category_progress?.length) {
      obj.categoryProgress = message.category_progress.map((e) => CategoryProgress.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TranscriptSummary>, I>>(base?: I): TranscriptSummary {
    return TranscriptSummary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TranscriptSummary>, I>>(object: I): TranscriptSummary {
    const message = createBaseTranscriptSummary();
    message.total_credits_earned = object.total_credits_earned ?? undefined;
    message.compulsory_credits_earned = object.compulsory_credits_earned ?? undefined;
    message.optional_credits_earned = object.optional_credits_earned ?? undefined;
    message.category_progress = object.category_progress?.map((e) => CategoryProgress.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTranscriptDiagnostic(): TranscriptDiagnostic {
  return { course_id: undefined, course_name: undefined, reason: undefined };
}

export const TranscriptDiagnostic: MessageFns<TranscriptDiagnostic> = {
  encode(message: TranscriptDiagnostic, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.course_id !== undefined) {
      ObjectId.encode(message.course_id, writer.uint32(10).fork()).join();
    }
    if (message.course_name !== undefined) {
      writer.uint32(18).string(message.course_name);
    }
    if (message.reason !== undefined) {
      writer.uint32(26).string(message.reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TranscriptDiagnostic {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTranscriptDiagnostic();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.course_id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.course_name = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.reason = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TranscriptDiagnostic {
    return {
      course_id: isSet(object.courseId) ? ObjectId.fromJSON(object.courseId) : undefined,
      course_name: isSet(object.courseName) ? globalThis.String(object.courseName) : undefined,
      reason: isSet(object.reason) ? globalThis.String(object.reason) : undefined,
    };
  },

  toJSON(message: TranscriptDiagnostic): unknown {
    const obj: any = {};
    if (message.course_id !== undefined) {
      obj.courseId = ObjectId.toJSON(message.course_id);
    }
    if (message.course_name !== undefined) {
      obj.courseName = message.course_name;
    }
    if (message.reason !== undefined) {
      obj.reason = message.reason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TranscriptDiagnostic>, I>>(base?: I): TranscriptDiagnostic {
    return TranscriptDiagnostic.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TranscriptDiagnostic>, I>>(object: I): TranscriptDiagnostic {
    const message = createBaseTranscriptDiagnostic();
    message.course_id = (object.course_id !== undefined && object.course_id !== null)
      ? ObjectId.fromPartial(object.course_id)
      : undefined;
    message.course_name = object.course_name ?? undefined;
    message.reason = object.reason ?? undefined;
    return message;
  },
};

function createBaseGetStudentTranscriptResponse(): GetStudentTranscriptResponse {
  return { header: undefined, rows: [], summary: undefined, diagnostics: [] };
}

export const GetStudentTranscriptResponse: MessageFns<GetStudentTranscriptResponse> = {
  encode(message: GetStudentTranscriptResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.header !== undefined) {
      TranscriptHeader.encode(message.header, writer.uint32(10).fork()).join();
    }
    for (const v of message.rows) {
      TranscriptRow.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.summary !== undefined) {
      TranscriptSummary.encode(message.summary, writer.uint32(26).fork()).join();
    }
    for (const v of message.diagnostics) {
      TranscriptDiagnostic.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStudentTranscriptResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStudentTranscriptResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.header = TranscriptHeader.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.rows.push(TranscriptRow.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.summary = TranscriptSummary.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.diagnostics.push(TranscriptDiagnostic.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetStudentTranscriptResponse {
    return {
      header: isSet(object.header) ? TranscriptHeader.fromJSON(object.header) : undefined,
      rows: globalThis.Array.isArray(object?.rows) ? object.rows.map((e: any) => TranscriptRow.fromJSON(e)) : [],
      summary: isSet(object.summary) ? TranscriptSummary.fromJSON(object.summary) : undefined,
      diagnostics: globalThis.Array.isArray(object?.diagnostics)
        ? object.diagnostics.map((e: any) => TranscriptDiagnostic.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetStudentTranscriptResponse): unknown {
    const obj: any = {};
    if (message.header !== undefined) {
      obj.header = TranscriptHeader.toJSON(message.header);
    }
    if (message.rows?.length) {
      obj.rows = message.rows.map((e) => TranscriptRow.toJSON(e));
    }
    if (message.summary !== undefined) {
      obj.summary = TranscriptSummary.toJSON(message.summary);
    }
    if (message.diagnostics?.length) {
      obj.diagnostics = message.diagnostics.map((e) => TranscriptDiagnostic.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStudentTranscriptResponse>, I>>(base?: I): GetStudentTranscriptResponse {
    return GetStudentTranscriptResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStudentTranscriptResponse>, I>>(object: I): GetStudentTranscriptResponse {
    const message = createBaseGetStudentTranscriptResponse();
    message.header = (object.header !== undefined && object.header !== null)
      ? TranscriptHeader.fromPartial(object.header)
      : undefined;
    message.rows = object.rows?.map((e) => TranscriptRow.fromPartial(e)) || [];
    message.summary = (object.summary !== undefined && object.summary !== null)
      ? TranscriptSummary.fromPartial(object.summary)
      : undefined;
    message.diagnostics = object.diagnostics?.map((e) => TranscriptDiagnostic.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetStudentDiplomaRequirementsRequest(): GetStudentDiplomaRequirementsRequest {
  return { context: undefined, student_id: undefined };
}

export const GetStudentDiplomaRequirementsRequest: MessageFns<GetStudentDiplomaRequirementsRequest> = {
  encode(message: GetStudentDiplomaRequirementsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.student_id !== undefined) {
      ObjectId.encode(message.student_id, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStudentDiplomaRequirementsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStudentDiplomaRequirementsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.student_id = ObjectId.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetStudentDiplomaRequirementsRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      student_id: isSet(object.studentId) ? ObjectId.fromJSON(object.studentId) : undefined,
    };
  },

  toJSON(message: GetStudentDiplomaRequirementsRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.student_id !== undefined) {
      obj.studentId = ObjectId.toJSON(message.student_id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStudentDiplomaRequirementsRequest>, I>>(
    base?: I,
  ): GetStudentDiplomaRequirementsRequest {
    return GetStudentDiplomaRequirementsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStudentDiplomaRequirementsRequest>, I>>(
    object: I,
  ): GetStudentDiplomaRequirementsRequest {
    const message = createBaseGetStudentDiplomaRequirementsRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.student_id = (object.student_id !== undefined && object.student_id !== null)
      ? ObjectId.fromPartial(object.student_id)
      : undefined;
    return message;
  },
};

function createBaseDiplomaRequirementRow(): DiplomaRequirementRow {
  return {
    label: undefined,
    is_group: undefined,
    group_sub_labels: [],
    total_required: undefined,
    earned_this_year: undefined,
    earned_to_date: undefined,
  };
}

export const DiplomaRequirementRow: MessageFns<DiplomaRequirementRow> = {
  encode(message: DiplomaRequirementRow, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.label !== undefined) {
      writer.uint32(10).string(message.label);
    }
    if (message.is_group !== undefined) {
      writer.uint32(16).bool(message.is_group);
    }
    for (const v of message.group_sub_labels) {
      writer.uint32(26).string(v!);
    }
    if (message.total_required !== undefined) {
      writer.uint32(33).double(message.total_required);
    }
    if (message.earned_this_year !== undefined) {
      writer.uint32(41).double(message.earned_this_year);
    }
    if (message.earned_to_date !== undefined) {
      writer.uint32(49).double(message.earned_to_date);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DiplomaRequirementRow {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDiplomaRequirementRow();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.label = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.is_group = reader.bool();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.group_sub_labels.push(reader.string());
          continue;
        case 4:
          if (tag !== 33) {
            break;
          }

          message.total_required = reader.double();
          continue;
        case 5:
          if (tag !== 41) {
            break;
          }

          message.earned_this_year = reader.double();
          continue;
        case 6:
          if (tag !== 49) {
            break;
          }

          message.earned_to_date = reader.double();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DiplomaRequirementRow {
    return {
      label: isSet(object.label) ? globalThis.String(object.label) : undefined,
      is_group: isSet(object.isGroup) ? globalThis.Boolean(object.isGroup) : undefined,
      group_sub_labels: globalThis.Array.isArray(object?.groupSubLabels)
        ? object.groupSubLabels.map((e: any) => globalThis.String(e))
        : [],
      total_required: isSet(object.totalRequired) ? globalThis.Number(object.totalRequired) : undefined,
      earned_this_year: isSet(object.earnedThisYear) ? globalThis.Number(object.earnedThisYear) : undefined,
      earned_to_date: isSet(object.earnedToDate) ? globalThis.Number(object.earnedToDate) : undefined,
    };
  },

  toJSON(message: DiplomaRequirementRow): unknown {
    const obj: any = {};
    if (message.label !== undefined) {
      obj.label = message.label;
    }
    if (message.is_group !== undefined) {
      obj.isGroup = message.is_group;
    }
    if (message.group_sub_labels?.length) {
      obj.groupSubLabels = message.group_sub_labels;
    }
    if (message.total_required !== undefined) {
      obj.totalRequired = message.total_required;
    }
    if (message.earned_this_year !== undefined) {
      obj.earnedThisYear = message.earned_this_year;
    }
    if (message.earned_to_date !== undefined) {
      obj.earnedToDate = message.earned_to_date;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DiplomaRequirementRow>, I>>(base?: I): DiplomaRequirementRow {
    return DiplomaRequirementRow.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DiplomaRequirementRow>, I>>(object: I): DiplomaRequirementRow {
    const message = createBaseDiplomaRequirementRow();
    message.label = object.label ?? undefined;
    message.is_group = object.is_group ?? undefined;
    message.group_sub_labels = object.group_sub_labels?.map((e) => e) || [];
    message.total_required = object.total_required ?? undefined;
    message.earned_this_year = object.earned_this_year ?? undefined;
    message.earned_to_date = object.earned_to_date ?? undefined;
    return message;
  },
};

function createBaseStudentGraduationTracking(): StudentGraduationTracking {
  return {
    id: undefined,
    student_id: undefined,
    community_involvement_hours_earned: undefined,
    literacy_requirement_completed: undefined,
    specialist_high_skills_major: undefined,
    online_learning_credits_earned: undefined,
    for_school_use_note: undefined,
  };
}

export const StudentGraduationTracking: MessageFns<StudentGraduationTracking> = {
  encode(message: StudentGraduationTracking, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      ObjectId.encode(message.id, writer.uint32(10).fork()).join();
    }
    if (message.student_id !== undefined) {
      ObjectId.encode(message.student_id, writer.uint32(18).fork()).join();
    }
    if (message.community_involvement_hours_earned !== undefined) {
      writer.uint32(25).double(message.community_involvement_hours_earned);
    }
    if (message.literacy_requirement_completed !== undefined) {
      writer.uint32(32).bool(message.literacy_requirement_completed);
    }
    if (message.specialist_high_skills_major !== undefined) {
      writer.uint32(42).string(message.specialist_high_skills_major);
    }
    if (message.online_learning_credits_earned !== undefined) {
      writer.uint32(49).double(message.online_learning_credits_earned);
    }
    if (message.for_school_use_note !== undefined) {
      writer.uint32(58).string(message.for_school_use_note);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StudentGraduationTracking {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStudentGraduationTracking();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.student_id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 25) {
            break;
          }

          message.community_involvement_hours_earned = reader.double();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.literacy_requirement_completed = reader.bool();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.specialist_high_skills_major = reader.string();
          continue;
        case 6:
          if (tag !== 49) {
            break;
          }

          message.online_learning_credits_earned = reader.double();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.for_school_use_note = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StudentGraduationTracking {
    return {
      id: isSet(object.id) ? ObjectId.fromJSON(object.id) : undefined,
      student_id: isSet(object.studentId) ? ObjectId.fromJSON(object.studentId) : undefined,
      community_involvement_hours_earned: isSet(object.communityInvolvementHoursEarned)
        ? globalThis.Number(object.communityInvolvementHoursEarned)
        : undefined,
      literacy_requirement_completed: isSet(object.literacyRequirementCompleted)
        ? globalThis.Boolean(object.literacyRequirementCompleted)
        : undefined,
      specialist_high_skills_major: isSet(object.specialistHighSkillsMajor)
        ? globalThis.String(object.specialistHighSkillsMajor)
        : undefined,
      online_learning_credits_earned: isSet(object.onlineLearningCreditsEarned)
        ? globalThis.Number(object.onlineLearningCreditsEarned)
        : undefined,
      for_school_use_note: isSet(object.forSchoolUseNote) ? globalThis.String(object.forSchoolUseNote) : undefined,
    };
  },

  toJSON(message: StudentGraduationTracking): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = ObjectId.toJSON(message.id);
    }
    if (message.student_id !== undefined) {
      obj.studentId = ObjectId.toJSON(message.student_id);
    }
    if (message.community_involvement_hours_earned !== undefined) {
      obj.communityInvolvementHoursEarned = message.community_involvement_hours_earned;
    }
    if (message.literacy_requirement_completed !== undefined) {
      obj.literacyRequirementCompleted = message.literacy_requirement_completed;
    }
    if (message.specialist_high_skills_major !== undefined) {
      obj.specialistHighSkillsMajor = message.specialist_high_skills_major;
    }
    if (message.online_learning_credits_earned !== undefined) {
      obj.onlineLearningCreditsEarned = message.online_learning_credits_earned;
    }
    if (message.for_school_use_note !== undefined) {
      obj.forSchoolUseNote = message.for_school_use_note;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StudentGraduationTracking>, I>>(base?: I): StudentGraduationTracking {
    return StudentGraduationTracking.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StudentGraduationTracking>, I>>(object: I): StudentGraduationTracking {
    const message = createBaseStudentGraduationTracking();
    message.id = (object.id !== undefined && object.id !== null) ? ObjectId.fromPartial(object.id) : undefined;
    message.student_id = (object.student_id !== undefined && object.student_id !== null)
      ? ObjectId.fromPartial(object.student_id)
      : undefined;
    message.community_involvement_hours_earned = object.community_involvement_hours_earned ?? undefined;
    message.literacy_requirement_completed = object.literacy_requirement_completed ?? undefined;
    message.specialist_high_skills_major = object.specialist_high_skills_major ?? undefined;
    message.online_learning_credits_earned = object.online_learning_credits_earned ?? undefined;
    message.for_school_use_note = object.for_school_use_note ?? undefined;
    return message;
  },
};

function createBaseGetStudentDiplomaRequirementsResponse(): GetStudentDiplomaRequirementsResponse {
  return {
    header: undefined,
    compulsory_rows: [],
    compulsory_total_required: undefined,
    compulsory_earned_this_year: undefined,
    compulsory_earned_to_date: undefined,
    optional_total_required: undefined,
    optional_earned_this_year: undefined,
    optional_earned_to_date: undefined,
    total_required: undefined,
    total_earned_this_year: undefined,
    total_earned_to_date: undefined,
    community_involvement_hours_required: undefined,
    community_involvement_hours_earned: undefined,
    online_learning_credits_required: undefined,
    online_learning_credits_earned: undefined,
    literacy_requirement_completed: undefined,
    specialist_high_skills_major: undefined,
    for_school_use_note: undefined,
    diagnostics: [],
  };
}

export const GetStudentDiplomaRequirementsResponse: MessageFns<GetStudentDiplomaRequirementsResponse> = {
  encode(message: GetStudentDiplomaRequirementsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.header !== undefined) {
      TranscriptHeader.encode(message.header, writer.uint32(10).fork()).join();
    }
    for (const v of message.compulsory_rows) {
      DiplomaRequirementRow.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.compulsory_total_required !== undefined) {
      writer.uint32(25).double(message.compulsory_total_required);
    }
    if (message.compulsory_earned_this_year !== undefined) {
      writer.uint32(33).double(message.compulsory_earned_this_year);
    }
    if (message.compulsory_earned_to_date !== undefined) {
      writer.uint32(41).double(message.compulsory_earned_to_date);
    }
    if (message.optional_total_required !== undefined) {
      writer.uint32(49).double(message.optional_total_required);
    }
    if (message.optional_earned_this_year !== undefined) {
      writer.uint32(57).double(message.optional_earned_this_year);
    }
    if (message.optional_earned_to_date !== undefined) {
      writer.uint32(65).double(message.optional_earned_to_date);
    }
    if (message.total_required !== undefined) {
      writer.uint32(73).double(message.total_required);
    }
    if (message.total_earned_this_year !== undefined) {
      writer.uint32(81).double(message.total_earned_this_year);
    }
    if (message.total_earned_to_date !== undefined) {
      writer.uint32(89).double(message.total_earned_to_date);
    }
    if (message.community_involvement_hours_required !== undefined) {
      writer.uint32(97).double(message.community_involvement_hours_required);
    }
    if (message.community_involvement_hours_earned !== undefined) {
      writer.uint32(105).double(message.community_involvement_hours_earned);
    }
    if (message.online_learning_credits_required !== undefined) {
      writer.uint32(113).double(message.online_learning_credits_required);
    }
    if (message.online_learning_credits_earned !== undefined) {
      writer.uint32(121).double(message.online_learning_credits_earned);
    }
    if (message.literacy_requirement_completed !== undefined) {
      writer.uint32(128).bool(message.literacy_requirement_completed);
    }
    if (message.specialist_high_skills_major !== undefined) {
      writer.uint32(138).string(message.specialist_high_skills_major);
    }
    if (message.for_school_use_note !== undefined) {
      writer.uint32(146).string(message.for_school_use_note);
    }
    for (const v of message.diagnostics) {
      TranscriptDiagnostic.encode(v!, writer.uint32(154).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStudentDiplomaRequirementsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStudentDiplomaRequirementsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.header = TranscriptHeader.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.compulsory_rows.push(DiplomaRequirementRow.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 25) {
            break;
          }

          message.compulsory_total_required = reader.double();
          continue;
        case 4:
          if (tag !== 33) {
            break;
          }

          message.compulsory_earned_this_year = reader.double();
          continue;
        case 5:
          if (tag !== 41) {
            break;
          }

          message.compulsory_earned_to_date = reader.double();
          continue;
        case 6:
          if (tag !== 49) {
            break;
          }

          message.optional_total_required = reader.double();
          continue;
        case 7:
          if (tag !== 57) {
            break;
          }

          message.optional_earned_this_year = reader.double();
          continue;
        case 8:
          if (tag !== 65) {
            break;
          }

          message.optional_earned_to_date = reader.double();
          continue;
        case 9:
          if (tag !== 73) {
            break;
          }

          message.total_required = reader.double();
          continue;
        case 10:
          if (tag !== 81) {
            break;
          }

          message.total_earned_this_year = reader.double();
          continue;
        case 11:
          if (tag !== 89) {
            break;
          }

          message.total_earned_to_date = reader.double();
          continue;
        case 12:
          if (tag !== 97) {
            break;
          }

          message.community_involvement_hours_required = reader.double();
          continue;
        case 13:
          if (tag !== 105) {
            break;
          }

          message.community_involvement_hours_earned = reader.double();
          continue;
        case 14:
          if (tag !== 113) {
            break;
          }

          message.online_learning_credits_required = reader.double();
          continue;
        case 15:
          if (tag !== 121) {
            break;
          }

          message.online_learning_credits_earned = reader.double();
          continue;
        case 16:
          if (tag !== 128) {
            break;
          }

          message.literacy_requirement_completed = reader.bool();
          continue;
        case 17:
          if (tag !== 138) {
            break;
          }

          message.specialist_high_skills_major = reader.string();
          continue;
        case 18:
          if (tag !== 146) {
            break;
          }

          message.for_school_use_note = reader.string();
          continue;
        case 19:
          if (tag !== 154) {
            break;
          }

          message.diagnostics.push(TranscriptDiagnostic.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetStudentDiplomaRequirementsResponse {
    return {
      header: isSet(object.header) ? TranscriptHeader.fromJSON(object.header) : undefined,
      compulsory_rows: globalThis.Array.isArray(object?.compulsoryRows)
        ? object.compulsoryRows.map((e: any) => DiplomaRequirementRow.fromJSON(e))
        : [],
      compulsory_total_required: isSet(object.compulsoryTotalRequired)
        ? globalThis.Number(object.compulsoryTotalRequired)
        : undefined,
      compulsory_earned_this_year: isSet(object.compulsoryEarnedThisYear)
        ? globalThis.Number(object.compulsoryEarnedThisYear)
        : undefined,
      compulsory_earned_to_date: isSet(object.compulsoryEarnedToDate)
        ? globalThis.Number(object.compulsoryEarnedToDate)
        : undefined,
      optional_total_required: isSet(object.optionalTotalRequired)
        ? globalThis.Number(object.optionalTotalRequired)
        : undefined,
      optional_earned_this_year: isSet(object.optionalEarnedThisYear)
        ? globalThis.Number(object.optionalEarnedThisYear)
        : undefined,
      optional_earned_to_date: isSet(object.optionalEarnedToDate)
        ? globalThis.Number(object.optionalEarnedToDate)
        : undefined,
      total_required: isSet(object.totalRequired) ? globalThis.Number(object.totalRequired) : undefined,
      total_earned_this_year: isSet(object.totalEarnedThisYear)
        ? globalThis.Number(object.totalEarnedThisYear)
        : undefined,
      total_earned_to_date: isSet(object.totalEarnedToDate) ? globalThis.Number(object.totalEarnedToDate) : undefined,
      community_involvement_hours_required: isSet(object.communityInvolvementHoursRequired)
        ? globalThis.Number(object.communityInvolvementHoursRequired)
        : undefined,
      community_involvement_hours_earned: isSet(object.communityInvolvementHoursEarned)
        ? globalThis.Number(object.communityInvolvementHoursEarned)
        : undefined,
      online_learning_credits_required: isSet(object.onlineLearningCreditsRequired)
        ? globalThis.Number(object.onlineLearningCreditsRequired)
        : undefined,
      online_learning_credits_earned: isSet(object.onlineLearningCreditsEarned)
        ? globalThis.Number(object.onlineLearningCreditsEarned)
        : undefined,
      literacy_requirement_completed: isSet(object.literacyRequirementCompleted)
        ? globalThis.Boolean(object.literacyRequirementCompleted)
        : undefined,
      specialist_high_skills_major: isSet(object.specialistHighSkillsMajor)
        ? globalThis.String(object.specialistHighSkillsMajor)
        : undefined,
      for_school_use_note: isSet(object.forSchoolUseNote) ? globalThis.String(object.forSchoolUseNote) : undefined,
      diagnostics: globalThis.Array.isArray(object?.diagnostics)
        ? object.diagnostics.map((e: any) => TranscriptDiagnostic.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetStudentDiplomaRequirementsResponse): unknown {
    const obj: any = {};
    if (message.header !== undefined) {
      obj.header = TranscriptHeader.toJSON(message.header);
    }
    if (message.compulsory_rows?.length) {
      obj.compulsoryRows = message.compulsory_rows.map((e) => DiplomaRequirementRow.toJSON(e));
    }
    if (message.compulsory_total_required !== undefined) {
      obj.compulsoryTotalRequired = message.compulsory_total_required;
    }
    if (message.compulsory_earned_this_year !== undefined) {
      obj.compulsoryEarnedThisYear = message.compulsory_earned_this_year;
    }
    if (message.compulsory_earned_to_date !== undefined) {
      obj.compulsoryEarnedToDate = message.compulsory_earned_to_date;
    }
    if (message.optional_total_required !== undefined) {
      obj.optionalTotalRequired = message.optional_total_required;
    }
    if (message.optional_earned_this_year !== undefined) {
      obj.optionalEarnedThisYear = message.optional_earned_this_year;
    }
    if (message.optional_earned_to_date !== undefined) {
      obj.optionalEarnedToDate = message.optional_earned_to_date;
    }
    if (message.total_required !== undefined) {
      obj.totalRequired = message.total_required;
    }
    if (message.total_earned_this_year !== undefined) {
      obj.totalEarnedThisYear = message.total_earned_this_year;
    }
    if (message.total_earned_to_date !== undefined) {
      obj.totalEarnedToDate = message.total_earned_to_date;
    }
    if (message.community_involvement_hours_required !== undefined) {
      obj.communityInvolvementHoursRequired = message.community_involvement_hours_required;
    }
    if (message.community_involvement_hours_earned !== undefined) {
      obj.communityInvolvementHoursEarned = message.community_involvement_hours_earned;
    }
    if (message.online_learning_credits_required !== undefined) {
      obj.onlineLearningCreditsRequired = message.online_learning_credits_required;
    }
    if (message.online_learning_credits_earned !== undefined) {
      obj.onlineLearningCreditsEarned = message.online_learning_credits_earned;
    }
    if (message.literacy_requirement_completed !== undefined) {
      obj.literacyRequirementCompleted = message.literacy_requirement_completed;
    }
    if (message.specialist_high_skills_major !== undefined) {
      obj.specialistHighSkillsMajor = message.specialist_high_skills_major;
    }
    if (message.for_school_use_note !== undefined) {
      obj.forSchoolUseNote = message.for_school_use_note;
    }
    if (message.diagnostics?.length) {
      obj.diagnostics = message.diagnostics.map((e) => TranscriptDiagnostic.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStudentDiplomaRequirementsResponse>, I>>(
    base?: I,
  ): GetStudentDiplomaRequirementsResponse {
    return GetStudentDiplomaRequirementsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStudentDiplomaRequirementsResponse>, I>>(
    object: I,
  ): GetStudentDiplomaRequirementsResponse {
    const message = createBaseGetStudentDiplomaRequirementsResponse();
    message.header = (object.header !== undefined && object.header !== null)
      ? TranscriptHeader.fromPartial(object.header)
      : undefined;
    message.compulsory_rows = object.compulsory_rows?.map((e) => DiplomaRequirementRow.fromPartial(e)) || [];
    message.compulsory_total_required = object.compulsory_total_required ?? undefined;
    message.compulsory_earned_this_year = object.compulsory_earned_this_year ?? undefined;
    message.compulsory_earned_to_date = object.compulsory_earned_to_date ?? undefined;
    message.optional_total_required = object.optional_total_required ?? undefined;
    message.optional_earned_this_year = object.optional_earned_this_year ?? undefined;
    message.optional_earned_to_date = object.optional_earned_to_date ?? undefined;
    message.total_required = object.total_required ?? undefined;
    message.total_earned_this_year = object.total_earned_this_year ?? undefined;
    message.total_earned_to_date = object.total_earned_to_date ?? undefined;
    message.community_involvement_hours_required = object.community_involvement_hours_required ?? undefined;
    message.community_involvement_hours_earned = object.community_involvement_hours_earned ?? undefined;
    message.online_learning_credits_required = object.online_learning_credits_required ?? undefined;
    message.online_learning_credits_earned = object.online_learning_credits_earned ?? undefined;
    message.literacy_requirement_completed = object.literacy_requirement_completed ?? undefined;
    message.specialist_high_skills_major = object.specialist_high_skills_major ?? undefined;
    message.for_school_use_note = object.for_school_use_note ?? undefined;
    message.diagnostics = object.diagnostics?.map((e) => TranscriptDiagnostic.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUpsertStudentGraduationTrackingRequest(): UpsertStudentGraduationTrackingRequest {
  return {
    context: undefined,
    student_id: undefined,
    community_involvement_hours_earned: undefined,
    literacy_requirement_completed: undefined,
    specialist_high_skills_major: undefined,
    online_learning_credits_earned: undefined,
    for_school_use_note: undefined,
  };
}

export const UpsertStudentGraduationTrackingRequest: MessageFns<UpsertStudentGraduationTrackingRequest> = {
  encode(message: UpsertStudentGraduationTrackingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.student_id !== undefined) {
      ObjectId.encode(message.student_id, writer.uint32(18).fork()).join();
    }
    if (message.community_involvement_hours_earned !== undefined) {
      writer.uint32(25).double(message.community_involvement_hours_earned);
    }
    if (message.literacy_requirement_completed !== undefined) {
      writer.uint32(32).bool(message.literacy_requirement_completed);
    }
    if (message.specialist_high_skills_major !== undefined) {
      writer.uint32(42).string(message.specialist_high_skills_major);
    }
    if (message.online_learning_credits_earned !== undefined) {
      writer.uint32(49).double(message.online_learning_credits_earned);
    }
    if (message.for_school_use_note !== undefined) {
      writer.uint32(58).string(message.for_school_use_note);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpsertStudentGraduationTrackingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpsertStudentGraduationTrackingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.student_id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 25) {
            break;
          }

          message.community_involvement_hours_earned = reader.double();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.literacy_requirement_completed = reader.bool();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.specialist_high_skills_major = reader.string();
          continue;
        case 6:
          if (tag !== 49) {
            break;
          }

          message.online_learning_credits_earned = reader.double();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.for_school_use_note = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpsertStudentGraduationTrackingRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      student_id: isSet(object.studentId) ? ObjectId.fromJSON(object.studentId) : undefined,
      community_involvement_hours_earned: isSet(object.communityInvolvementHoursEarned)
        ? globalThis.Number(object.communityInvolvementHoursEarned)
        : undefined,
      literacy_requirement_completed: isSet(object.literacyRequirementCompleted)
        ? globalThis.Boolean(object.literacyRequirementCompleted)
        : undefined,
      specialist_high_skills_major: isSet(object.specialistHighSkillsMajor)
        ? globalThis.String(object.specialistHighSkillsMajor)
        : undefined,
      online_learning_credits_earned: isSet(object.onlineLearningCreditsEarned)
        ? globalThis.Number(object.onlineLearningCreditsEarned)
        : undefined,
      for_school_use_note: isSet(object.forSchoolUseNote) ? globalThis.String(object.forSchoolUseNote) : undefined,
    };
  },

  toJSON(message: UpsertStudentGraduationTrackingRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.student_id !== undefined) {
      obj.studentId = ObjectId.toJSON(message.student_id);
    }
    if (message.community_involvement_hours_earned !== undefined) {
      obj.communityInvolvementHoursEarned = message.community_involvement_hours_earned;
    }
    if (message.literacy_requirement_completed !== undefined) {
      obj.literacyRequirementCompleted = message.literacy_requirement_completed;
    }
    if (message.specialist_high_skills_major !== undefined) {
      obj.specialistHighSkillsMajor = message.specialist_high_skills_major;
    }
    if (message.online_learning_credits_earned !== undefined) {
      obj.onlineLearningCreditsEarned = message.online_learning_credits_earned;
    }
    if (message.for_school_use_note !== undefined) {
      obj.forSchoolUseNote = message.for_school_use_note;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpsertStudentGraduationTrackingRequest>, I>>(
    base?: I,
  ): UpsertStudentGraduationTrackingRequest {
    return UpsertStudentGraduationTrackingRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpsertStudentGraduationTrackingRequest>, I>>(
    object: I,
  ): UpsertStudentGraduationTrackingRequest {
    const message = createBaseUpsertStudentGraduationTrackingRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.student_id = (object.student_id !== undefined && object.student_id !== null)
      ? ObjectId.fromPartial(object.student_id)
      : undefined;
    message.community_involvement_hours_earned = object.community_involvement_hours_earned ?? undefined;
    message.literacy_requirement_completed = object.literacy_requirement_completed ?? undefined;
    message.specialist_high_skills_major = object.specialist_high_skills_major ?? undefined;
    message.online_learning_credits_earned = object.online_learning_credits_earned ?? undefined;
    message.for_school_use_note = object.for_school_use_note ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
