// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: user_service/action_required_by_parents.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ObjectId } from "../utils/object_id";

export const protobufPackage = "user_service";

export enum ActionType {
  PAY_INVOICE = "PAY_INVOICE",
  FILL_FIELDS = "FILL_FIELDS",
  CORRECT_FIELDS = "CORRECT_FIELDS",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function actionTypeFromJSON(object: any): ActionType {
  switch (object) {
    case 0:
    case "PAY_INVOICE":
      return ActionType.PAY_INVOICE;
    case 1:
    case "FILL_FIELDS":
      return ActionType.FILL_FIELDS;
    case 2:
    case "CORRECT_FIELDS":
      return ActionType.CORRECT_FIELDS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ActionType.UNRECOGNIZED;
  }
}

export function actionTypeToJSON(object: ActionType): string {
  switch (object) {
    case ActionType.PAY_INVOICE:
      return "PAY_INVOICE";
    case ActionType.FILL_FIELDS:
      return "FILL_FIELDS";
    case ActionType.CORRECT_FIELDS:
      return "CORRECT_FIELDS";
    case ActionType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function actionTypeToNumber(object: ActionType): number {
  switch (object) {
    case ActionType.PAY_INVOICE:
      return 0;
    case ActionType.FILL_FIELDS:
      return 1;
    case ActionType.CORRECT_FIELDS:
      return 2;
    case ActionType.UNRECOGNIZED:
    default:
      return -1;
  }
}

export interface ActionRequiredByParents {
  action_type: ActionType;
  title: string;
  invoice_id?: ObjectId | undefined;
  group_id?: ObjectId | undefined;
}

function createBaseActionRequiredByParents(): ActionRequiredByParents {
  return { action_type: ActionType.PAY_INVOICE, title: "", invoice_id: undefined, group_id: undefined };
}

export const ActionRequiredByParents: MessageFns<ActionRequiredByParents> = {
  encode(message: ActionRequiredByParents, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.action_type !== ActionType.PAY_INVOICE) {
      writer.uint32(8).int32(actionTypeToNumber(message.action_type));
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.invoice_id !== undefined) {
      ObjectId.encode(message.invoice_id, writer.uint32(26).fork()).join();
    }
    if (message.group_id !== undefined) {
      ObjectId.encode(message.group_id, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActionRequiredByParents {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActionRequiredByParents();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.action_type = actionTypeFromJSON(reader.int32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.invoice_id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.group_id = ObjectId.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActionRequiredByParents {
    return {
      action_type: isSet(object.action_type) ? actionTypeFromJSON(object.action_type) : ActionType.PAY_INVOICE,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      invoice_id: isSet(object.invoice_id) ? ObjectId.fromJSON(object.invoice_id) : undefined,
      group_id: isSet(object.group_id) ? ObjectId.fromJSON(object.group_id) : undefined,
    };
  },

  toJSON(message: ActionRequiredByParents): unknown {
    const obj: any = {};
    if (message.action_type !== ActionType.PAY_INVOICE) {
      obj.action_type = actionTypeToJSON(message.action_type);
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.invoice_id !== undefined) {
      obj.invoice_id = ObjectId.toJSON(message.invoice_id);
    }
    if (message.group_id !== undefined) {
      obj.group_id = ObjectId.toJSON(message.group_id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActionRequiredByParents>, I>>(base?: I): ActionRequiredByParents {
    return ActionRequiredByParents.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActionRequiredByParents>, I>>(object: I): ActionRequiredByParents {
    const message = createBaseActionRequiredByParents();
    message.action_type = object.action_type ?? ActionType.PAY_INVOICE;
    message.title = object.title ?? "";
    message.invoice_id = (object.invoice_id !== undefined && object.invoice_id !== null)
      ? ObjectId.fromPartial(object.invoice_id)
      : undefined;
    message.group_id = (object.group_id !== undefined && object.group_id !== null)
      ? ObjectId.fromPartial(object.group_id)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
