// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: user_service/custom_fields_template.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  ProfileSection,
  profileSectionFromJSON,
  profileSectionToJSON,
  profileSectionToNumber,
} from "../organization_service/organization_profile_settings";
import { ObjectId } from "../utils/object_id";
import { UserType, userTypeFromJSON, userTypeToJSON, userTypeToNumber } from "../utils/user_type";
import {
  CustomFieldType,
  customFieldTypeFromJSON,
  customFieldTypeToJSON,
  customFieldTypeToNumber,
} from "./custom_field";
import { StudentStatus, studentStatusFromJSON, studentStatusToJSON, studentStatusToNumber } from "./student";

export const protobufPackage = "user_service";

/** Template field definition (field within a template group) */
export interface TemplateFieldDefinition {
  field_id: ObjectId | undefined;
  field_name: string;
  field_type: CustomFieldType;
  field_is_required: boolean;
  field_description: string;
  field_regex_pattern?: string | undefined;
  field_options: string[];
}

/** Template group definition (group within a template) */
export interface TemplateGroupDefinition {
  group_id: ObjectId | undefined;
  group_name: string;
  group_user_type: UserType;
  group_profile_section: ProfileSection;
  group_hints: string[];
  group_field_definitions: TemplateFieldDefinition[];
  group_visible_to_parents_for_statuses: StudentStatus[];
  group_visible_to_teachers_for_statuses: StudentStatus[];
}

/** Custom fields template (global template not tied to organization) */
export interface CustomFieldsTemplate {
  template_id: ObjectId | undefined;
  template_name: string;
  template_description: string;
  template_is_active: boolean;
  template_groups: TemplateGroupDefinition[];
}

/** Organization used templates (tracks which templates an organization uses) */
export interface OrganizationUsedTemplates {
  id: ObjectId | undefined;
  organization_id:
    | ObjectId
    | undefined;
  /** Template IDs */
  templates: ObjectId[];
}

function createBaseTemplateFieldDefinition(): TemplateFieldDefinition {
  return {
    field_id: undefined,
    field_name: "",
    field_type: CustomFieldType.STRING,
    field_is_required: false,
    field_description: "",
    field_regex_pattern: "",
    field_options: [],
  };
}

export const TemplateFieldDefinition: MessageFns<TemplateFieldDefinition> = {
  encode(message: TemplateFieldDefinition, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.field_id !== undefined) {
      ObjectId.encode(message.field_id, writer.uint32(10).fork()).join();
    }
    if (message.field_name !== "") {
      writer.uint32(18).string(message.field_name);
    }
    if (message.field_type !== CustomFieldType.STRING) {
      writer.uint32(24).int32(customFieldTypeToNumber(message.field_type));
    }
    if (message.field_is_required !== false) {
      writer.uint32(32).bool(message.field_is_required);
    }
    if (message.field_description !== "") {
      writer.uint32(42).string(message.field_description);
    }
    if (message.field_regex_pattern !== undefined && message.field_regex_pattern !== "") {
      writer.uint32(50).string(message.field_regex_pattern);
    }
    for (const v of message.field_options) {
      writer.uint32(58).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TemplateFieldDefinition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTemplateFieldDefinition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.field_id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.field_name = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.field_type = customFieldTypeFromJSON(reader.int32());
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.field_is_required = reader.bool();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.field_description = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.field_regex_pattern = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.field_options.push(reader.string());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TemplateFieldDefinition {
    return {
      field_id: isSet(object.field_id) ? ObjectId.fromJSON(object.field_id) : undefined,
      field_name: isSet(object.field_name) ? globalThis.String(object.field_name) : "",
      field_type: isSet(object.field_type) ? customFieldTypeFromJSON(object.field_type) : CustomFieldType.STRING,
      field_is_required: isSet(object.field_is_required) ? globalThis.Boolean(object.field_is_required) : false,
      field_description: isSet(object.field_description) ? globalThis.String(object.field_description) : "",
      field_regex_pattern: isSet(object.field_regex_pattern) ? globalThis.String(object.field_regex_pattern) : "",
      field_options: globalThis.Array.isArray(object?.field_options)
        ? object.field_options.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: TemplateFieldDefinition): unknown {
    const obj: any = {};
    if (message.field_id !== undefined) {
      obj.field_id = ObjectId.toJSON(message.field_id);
    }
    if (message.field_name !== "") {
      obj.field_name = message.field_name;
    }
    if (message.field_type !== CustomFieldType.STRING) {
      obj.field_type = customFieldTypeToJSON(message.field_type);
    }
    if (message.field_is_required !== false) {
      obj.field_is_required = message.field_is_required;
    }
    if (message.field_description !== "") {
      obj.field_description = message.field_description;
    }
    if (message.field_regex_pattern !== undefined && message.field_regex_pattern !== "") {
      obj.field_regex_pattern = message.field_regex_pattern;
    }
    if (message.field_options?.length) {
      obj.field_options = message.field_options;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TemplateFieldDefinition>, I>>(base?: I): TemplateFieldDefinition {
    return TemplateFieldDefinition.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TemplateFieldDefinition>, I>>(object: I): TemplateFieldDefinition {
    const message = createBaseTemplateFieldDefinition();
    message.field_id = (object.field_id !== undefined && object.field_id !== null)
      ? ObjectId.fromPartial(object.field_id)
      : undefined;
    message.field_name = object.field_name ?? "";
    message.field_type = object.field_type ?? CustomFieldType.STRING;
    message.field_is_required = object.field_is_required ?? false;
    message.field_description = object.field_description ?? "";
    message.field_regex_pattern = object.field_regex_pattern ?? "";
    message.field_options = object.field_options?.map((e) => e) || [];
    return message;
  },
};

function createBaseTemplateGroupDefinition(): TemplateGroupDefinition {
  return {
    group_id: undefined,
    group_name: "",
    group_user_type: UserType.NONE,
    group_profile_section: ProfileSection.OVERVIEW,
    group_hints: [],
    group_field_definitions: [],
    group_visible_to_parents_for_statuses: [],
    group_visible_to_teachers_for_statuses: [],
  };
}

export const TemplateGroupDefinition: MessageFns<TemplateGroupDefinition> = {
  encode(message: TemplateGroupDefinition, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.group_id !== undefined) {
      ObjectId.encode(message.group_id, writer.uint32(10).fork()).join();
    }
    if (message.group_name !== "") {
      writer.uint32(18).string(message.group_name);
    }
    if (message.group_user_type !== UserType.NONE) {
      writer.uint32(24).int32(userTypeToNumber(message.group_user_type));
    }
    if (message.group_profile_section !== ProfileSection.OVERVIEW) {
      writer.uint32(32).int32(profileSectionToNumber(message.group_profile_section));
    }
    for (const v of message.group_hints) {
      writer.uint32(42).string(v!);
    }
    for (const v of message.group_field_definitions) {
      TemplateFieldDefinition.encode(v!, writer.uint32(50).fork()).join();
    }
    writer.uint32(58).fork();
    for (const v of message.group_visible_to_parents_for_statuses) {
      writer.int32(studentStatusToNumber(v));
    }
    writer.join();
    writer.uint32(66).fork();
    for (const v of message.group_visible_to_teachers_for_statuses) {
      writer.int32(studentStatusToNumber(v));
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TemplateGroupDefinition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTemplateGroupDefinition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.group_id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.group_name = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.group_user_type = userTypeFromJSON(reader.int32());
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.group_profile_section = profileSectionFromJSON(reader.int32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.group_hints.push(reader.string());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.group_field_definitions.push(TemplateFieldDefinition.decode(reader, reader.uint32()));
          continue;
        case 7:
          if (tag === 56) {
            message.group_visible_to_parents_for_statuses.push(studentStatusFromJSON(reader.int32()));

            continue;
          }

          if (tag === 58) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.group_visible_to_parents_for_statuses.push(studentStatusFromJSON(reader.int32()));
            }

            continue;
          }

          break;
        case 8:
          if (tag === 64) {
            message.group_visible_to_teachers_for_statuses.push(studentStatusFromJSON(reader.int32()));

            continue;
          }

          if (tag === 66) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.group_visible_to_teachers_for_statuses.push(studentStatusFromJSON(reader.int32()));
            }

            continue;
          }

          break;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TemplateGroupDefinition {
    return {
      group_id: isSet(object.group_id) ? ObjectId.fromJSON(object.group_id) : undefined,
      group_name: isSet(object.group_name) ? globalThis.String(object.group_name) : "",
      group_user_type: isSet(object.group_user_type) ? userTypeFromJSON(object.group_user_type) : UserType.NONE,
      group_profile_section: isSet(object.group_profile_section)
        ? profileSectionFromJSON(object.group_profile_section)
        : ProfileSection.OVERVIEW,
      group_hints: globalThis.Array.isArray(object?.group_hints)
        ? object.group_hints.map((e: any) => globalThis.String(e))
        : [],
      group_field_definitions: globalThis.Array.isArray(object?.group_field_definitions)
        ? object.group_field_definitions.map((e: any) => TemplateFieldDefinition.fromJSON(e))
        : [],
      group_visible_to_parents_for_statuses: globalThis.Array.isArray(object?.group_visible_to_parents_for_statuses)
        ? object.group_visible_to_parents_for_statuses.map((e: any) => studentStatusFromJSON(e))
        : [],
      group_visible_to_teachers_for_statuses: globalThis.Array.isArray(object?.group_visible_to_teachers_for_statuses)
        ? object.group_visible_to_teachers_for_statuses.map((e: any) => studentStatusFromJSON(e))
        : [],
    };
  },

  toJSON(message: TemplateGroupDefinition): unknown {
    const obj: any = {};
    if (message.group_id !== undefined) {
      obj.group_id = ObjectId.toJSON(message.group_id);
    }
    if (message.group_name !== "") {
      obj.group_name = message.group_name;
    }
    if (message.group_user_type !== UserType.NONE) {
      obj.group_user_type = userTypeToJSON(message.group_user_type);
    }
    if (message.group_profile_section !== ProfileSection.OVERVIEW) {
      obj.group_profile_section = profileSectionToJSON(message.group_profile_section);
    }
    if (message.group_hints?.length) {
      obj.group_hints = message.group_hints;
    }
    if (message.group_field_definitions?.length) {
      obj.group_field_definitions = message.group_field_definitions.map((e) => TemplateFieldDefinition.toJSON(e));
    }
    if (message.group_visible_to_parents_for_statuses?.length) {
      obj.group_visible_to_parents_for_statuses = message.group_visible_to_parents_for_statuses.map((e) =>
        studentStatusToJSON(e)
      );
    }
    if (message.group_visible_to_teachers_for_statuses?.length) {
      obj.group_visible_to_teachers_for_statuses = message.group_visible_to_teachers_for_statuses.map((e) =>
        studentStatusToJSON(e)
      );
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TemplateGroupDefinition>, I>>(base?: I): TemplateGroupDefinition {
    return TemplateGroupDefinition.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TemplateGroupDefinition>, I>>(object: I): TemplateGroupDefinition {
    const message = createBaseTemplateGroupDefinition();
    message.group_id = (object.group_id !== undefined && object.group_id !== null)
      ? ObjectId.fromPartial(object.group_id)
      : undefined;
    message.group_name = object.group_name ?? "";
    message.group_user_type = object.group_user_type ?? UserType.NONE;
    message.group_profile_section = object.group_profile_section ?? ProfileSection.OVERVIEW;
    message.group_hints = object.group_hints?.map((e) => e) || [];
    message.group_field_definitions =
      object.group_field_definitions?.map((e) => TemplateFieldDefinition.fromPartial(e)) || [];
    message.group_visible_to_parents_for_statuses = object.group_visible_to_parents_for_statuses?.map((e) => e) || [];
    message.group_visible_to_teachers_for_statuses = object.group_visible_to_teachers_for_statuses?.map((e) => e) || [];
    return message;
  },
};

function createBaseCustomFieldsTemplate(): CustomFieldsTemplate {
  return {
    template_id: undefined,
    template_name: "",
    template_description: "",
    template_is_active: false,
    template_groups: [],
  };
}

export const CustomFieldsTemplate: MessageFns<CustomFieldsTemplate> = {
  encode(message: CustomFieldsTemplate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.template_id !== undefined) {
      ObjectId.encode(message.template_id, writer.uint32(10).fork()).join();
    }
    if (message.template_name !== "") {
      writer.uint32(18).string(message.template_name);
    }
    if (message.template_description !== "") {
      writer.uint32(26).string(message.template_description);
    }
    if (message.template_is_active !== false) {
      writer.uint32(32).bool(message.template_is_active);
    }
    for (const v of message.template_groups) {
      TemplateGroupDefinition.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CustomFieldsTemplate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCustomFieldsTemplate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.template_id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.template_name = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.template_description = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.template_is_active = reader.bool();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.template_groups.push(TemplateGroupDefinition.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CustomFieldsTemplate {
    return {
      template_id: isSet(object.template_id) ? ObjectId.fromJSON(object.template_id) : undefined,
      template_name: isSet(object.template_name) ? globalThis.String(object.template_name) : "",
      template_description: isSet(object.template_description) ? globalThis.String(object.template_description) : "",
      template_is_active: isSet(object.template_is_active) ? globalThis.Boolean(object.template_is_active) : false,
      template_groups: globalThis.Array.isArray(object?.template_groups)
        ? object.template_groups.map((e: any) => TemplateGroupDefinition.fromJSON(e))
        : [],
    };
  },

  toJSON(message: CustomFieldsTemplate): unknown {
    const obj: any = {};
    if (message.template_id !== undefined) {
      obj.template_id = ObjectId.toJSON(message.template_id);
    }
    if (message.template_name !== "") {
      obj.template_name = message.template_name;
    }
    if (message.template_description !== "") {
      obj.template_description = message.template_description;
    }
    if (message.template_is_active !== false) {
      obj.template_is_active = message.template_is_active;
    }
    if (message.template_groups?.length) {
      obj.template_groups = message.template_groups.map((e) => TemplateGroupDefinition.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CustomFieldsTemplate>, I>>(base?: I): CustomFieldsTemplate {
    return CustomFieldsTemplate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CustomFieldsTemplate>, I>>(object: I): CustomFieldsTemplate {
    const message = createBaseCustomFieldsTemplate();
    message.template_id = (object.template_id !== undefined && object.template_id !== null)
      ? ObjectId.fromPartial(object.template_id)
      : undefined;
    message.template_name = object.template_name ?? "";
    message.template_description = object.template_description ?? "";
    message.template_is_active = object.template_is_active ?? false;
    message.template_groups = object.template_groups?.map((e) => TemplateGroupDefinition.fromPartial(e)) || [];
    return message;
  },
};

function createBaseOrganizationUsedTemplates(): OrganizationUsedTemplates {
  return { id: undefined, organization_id: undefined, templates: [] };
}

export const OrganizationUsedTemplates: MessageFns<OrganizationUsedTemplates> = {
  encode(message: OrganizationUsedTemplates, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      ObjectId.encode(message.id, writer.uint32(10).fork()).join();
    }
    if (message.organization_id !== undefined) {
      ObjectId.encode(message.organization_id, writer.uint32(18).fork()).join();
    }
    for (const v of message.templates) {
      ObjectId.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrganizationUsedTemplates {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrganizationUsedTemplates();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.organization_id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.templates.push(ObjectId.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrganizationUsedTemplates {
    return {
      id: isSet(object.id) ? ObjectId.fromJSON(object.id) : undefined,
      organization_id: isSet(object.organization_id) ? ObjectId.fromJSON(object.organization_id) : undefined,
      templates: globalThis.Array.isArray(object?.templates)
        ? object.templates.map((e: any) => ObjectId.fromJSON(e))
        : [],
    };
  },

  toJSON(message: OrganizationUsedTemplates): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = ObjectId.toJSON(message.id);
    }
    if (message.organization_id !== undefined) {
      obj.organization_id = ObjectId.toJSON(message.organization_id);
    }
    if (message.templates?.length) {
      obj.templates = message.templates.map((e) => ObjectId.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrganizationUsedTemplates>, I>>(base?: I): OrganizationUsedTemplates {
    return OrganizationUsedTemplates.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrganizationUsedTemplates>, I>>(object: I): OrganizationUsedTemplates {
    const message = createBaseOrganizationUsedTemplates();
    message.id = (object.id !== undefined && object.id !== null) ? ObjectId.fromPartial(object.id) : undefined;
    message.organization_id = (object.organization_id !== undefined && object.organization_id !== null)
      ? ObjectId.fromPartial(object.organization_id)
      : undefined;
    message.templates = object.templates?.map((e) => ObjectId.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
