// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: user_service/device_token_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ObjectId } from "../utils/object_id";
import { RequestContext } from "../utils/request_context";
import {
  DevicePlatform,
  devicePlatformFromJSON,
  devicePlatformToJSON,
  devicePlatformToNumber,
  DeviceToken,
} from "./device_token";

export const protobufPackage = "user_service";

export interface RefreshDeviceTokenRequest {
  context: RequestContext | undefined;
  token: string;
  platform: DevicePlatform;
  device_id: string;
  app_version: string;
}

export interface DisableDeviceTokenRequest {
  context: RequestContext | undefined;
  token: string;
  user_id: ObjectId | undefined;
}

export interface DisableDeviceTokenResponse {
  success: boolean;
  disabled_count?: number | undefined;
}

export interface ListDeviceTokensRequest {
  context: RequestContext | undefined;
  user_id: ObjectId | undefined;
}

export interface DeviceTokenList {
  tokens: DeviceToken[];
  tokens_count: number;
}

function createBaseRefreshDeviceTokenRequest(): RefreshDeviceTokenRequest {
  return {
    context: undefined,
    token: "",
    platform: DevicePlatform.DEVICE_PLATFORM_UNKNOWN,
    device_id: "",
    app_version: "",
  };
}

export const RefreshDeviceTokenRequest: MessageFns<RefreshDeviceTokenRequest> = {
  encode(message: RefreshDeviceTokenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.token !== "") {
      writer.uint32(18).string(message.token);
    }
    if (message.platform !== DevicePlatform.DEVICE_PLATFORM_UNKNOWN) {
      writer.uint32(24).int32(devicePlatformToNumber(message.platform));
    }
    if (message.device_id !== "") {
      writer.uint32(34).string(message.device_id);
    }
    if (message.app_version !== "") {
      writer.uint32(42).string(message.app_version);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefreshDeviceTokenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRefreshDeviceTokenRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.token = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.platform = devicePlatformFromJSON(reader.int32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.device_id = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.app_version = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RefreshDeviceTokenRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      platform: isSet(object.platform)
        ? devicePlatformFromJSON(object.platform)
        : DevicePlatform.DEVICE_PLATFORM_UNKNOWN,
      device_id: isSet(object.deviceId) ? globalThis.String(object.deviceId) : "",
      app_version: isSet(object.appVersion) ? globalThis.String(object.appVersion) : "",
    };
  },

  toJSON(message: RefreshDeviceTokenRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.platform !== DevicePlatform.DEVICE_PLATFORM_UNKNOWN) {
      obj.platform = devicePlatformToJSON(message.platform);
    }
    if (message.device_id !== "") {
      obj.deviceId = message.device_id;
    }
    if (message.app_version !== "") {
      obj.appVersion = message.app_version;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RefreshDeviceTokenRequest>, I>>(base?: I): RefreshDeviceTokenRequest {
    return RefreshDeviceTokenRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefreshDeviceTokenRequest>, I>>(object: I): RefreshDeviceTokenRequest {
    const message = createBaseRefreshDeviceTokenRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.token = object.token ?? "";
    message.platform = object.platform ?? DevicePlatform.DEVICE_PLATFORM_UNKNOWN;
    message.device_id = object.device_id ?? "";
    message.app_version = object.app_version ?? "";
    return message;
  },
};

function createBaseDisableDeviceTokenRequest(): DisableDeviceTokenRequest {
  return { context: undefined, token: "", user_id: undefined };
}

export const DisableDeviceTokenRequest: MessageFns<DisableDeviceTokenRequest> = {
  encode(message: DisableDeviceTokenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.token !== "") {
      writer.uint32(18).string(message.token);
    }
    if (message.user_id !== undefined) {
      ObjectId.encode(message.user_id, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DisableDeviceTokenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDisableDeviceTokenRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.token = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.user_id = ObjectId.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DisableDeviceTokenRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      user_id: isSet(object.userId) ? ObjectId.fromJSON(object.userId) : undefined,
    };
  },

  toJSON(message: DisableDeviceTokenRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.user_id !== undefined) {
      obj.userId = ObjectId.toJSON(message.user_id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DisableDeviceTokenRequest>, I>>(base?: I): DisableDeviceTokenRequest {
    return DisableDeviceTokenRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DisableDeviceTokenRequest>, I>>(object: I): DisableDeviceTokenRequest {
    const message = createBaseDisableDeviceTokenRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.token = object.token ?? "";
    message.user_id = (object.user_id !== undefined && object.user_id !== null)
      ? ObjectId.fromPartial(object.user_id)
      : undefined;
    return message;
  },
};

function createBaseDisableDeviceTokenResponse(): DisableDeviceTokenResponse {
  return { success: false, disabled_count: 0 };
}

export const DisableDeviceTokenResponse: MessageFns<DisableDeviceTokenResponse> = {
  encode(message: DisableDeviceTokenResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.disabled_count !== undefined && message.disabled_count !== 0) {
      writer.uint32(16).uint64(message.disabled_count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DisableDeviceTokenResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDisableDeviceTokenResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.disabled_count = longToNumber(reader.uint64());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DisableDeviceTokenResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      disabled_count: isSet(object.disabledCount) ? globalThis.Number(object.disabledCount) : 0,
    };
  },

  toJSON(message: DisableDeviceTokenResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.disabled_count !== undefined && message.disabled_count !== 0) {
      obj.disabledCount = Math.round(message.disabled_count);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DisableDeviceTokenResponse>, I>>(base?: I): DisableDeviceTokenResponse {
    return DisableDeviceTokenResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DisableDeviceTokenResponse>, I>>(object: I): DisableDeviceTokenResponse {
    const message = createBaseDisableDeviceTokenResponse();
    message.success = object.success ?? false;
    message.disabled_count = object.disabled_count ?? 0;
    return message;
  },
};

function createBaseListDeviceTokensRequest(): ListDeviceTokensRequest {
  return { context: undefined, user_id: undefined };
}

export const ListDeviceTokensRequest: MessageFns<ListDeviceTokensRequest> = {
  encode(message: ListDeviceTokensRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.user_id !== undefined) {
      ObjectId.encode(message.user_id, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListDeviceTokensRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListDeviceTokensRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.user_id = ObjectId.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListDeviceTokensRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      user_id: isSet(object.userId) ? ObjectId.fromJSON(object.userId) : undefined,
    };
  },

  toJSON(message: ListDeviceTokensRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.user_id !== undefined) {
      obj.userId = ObjectId.toJSON(message.user_id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListDeviceTokensRequest>, I>>(base?: I): ListDeviceTokensRequest {
    return ListDeviceTokensRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListDeviceTokensRequest>, I>>(object: I): ListDeviceTokensRequest {
    const message = createBaseListDeviceTokensRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.user_id = (object.user_id !== undefined && object.user_id !== null)
      ? ObjectId.fromPartial(object.user_id)
      : undefined;
    return message;
  },
};

function createBaseDeviceTokenList(): DeviceTokenList {
  return { tokens: [], tokens_count: 0 };
}

export const DeviceTokenList: MessageFns<DeviceTokenList> = {
  encode(message: DeviceTokenList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tokens) {
      DeviceToken.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.tokens_count !== 0) {
      writer.uint32(16).uint64(message.tokens_count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeviceTokenList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeviceTokenList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.tokens.push(DeviceToken.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.tokens_count = longToNumber(reader.uint64());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeviceTokenList {
    return {
      tokens: globalThis.Array.isArray(object?.tokens) ? object.tokens.map((e: any) => DeviceToken.fromJSON(e)) : [],
      tokens_count: isSet(object.tokensCount) ? globalThis.Number(object.tokensCount) : 0,
    };
  },

  toJSON(message: DeviceTokenList): unknown {
    const obj: any = {};
    if (message.tokens?.length) {
      obj.tokens = message.tokens.map((e) => DeviceToken.toJSON(e));
    }
    if (message.tokens_count !== 0) {
      obj.tokensCount = Math.round(message.tokens_count);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeviceTokenList>, I>>(base?: I): DeviceTokenList {
    return DeviceTokenList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeviceTokenList>, I>>(object: I): DeviceTokenList {
    const message = createBaseDeviceTokenList();
    message.tokens = object.tokens?.map((e) => DeviceToken.fromPartial(e)) || [];
    message.tokens_count = object.tokens_count ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
