// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: user_service/teacher.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";
import { ObjectId } from "../utils/object_id";
import { PhoneNumber } from "../utils/phone_number";
import { UserRole, userRoleFromJSON, userRoleToJSON, userRoleToNumber } from "./user_role";

export const protobufPackage = "user_service";

export enum TeacherStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function teacherStatusFromJSON(object: any): TeacherStatus {
  switch (object) {
    case 0:
    case "ACTIVE":
      return TeacherStatus.ACTIVE;
    case 1:
    case "INACTIVE":
      return TeacherStatus.INACTIVE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TeacherStatus.UNRECOGNIZED;
  }
}

export function teacherStatusToJSON(object: TeacherStatus): string {
  switch (object) {
    case TeacherStatus.ACTIVE:
      return "ACTIVE";
    case TeacherStatus.INACTIVE:
      return "INACTIVE";
    case TeacherStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function teacherStatusToNumber(object: TeacherStatus): number {
  switch (object) {
    case TeacherStatus.ACTIVE:
      return 0;
    case TeacherStatus.INACTIVE:
      return 1;
    case TeacherStatus.UNRECOGNIZED:
    default:
      return -1;
  }
}

/** Basic teacher model with only essential fields */
export interface TeacherBasic {
  id: ObjectId | undefined;
  organization: ObjectId | undefined;
  username: string;
  emailDomain: string;
  email: string;
  firstName: string;
  lastName: string;
}

/** Full teacher model with all fields */
export interface Teacher {
  id: ObjectId | undefined;
  status: TeacherStatus;
  username: string;
  emailDomain: string;
  firstName: string;
  lastName: string;
  gender: string;
  email: string;
  personalEmail: string;
  dateOfBirth: Date | undefined;
  phoneNumber: PhoneNumber | undefined;
  signatureFileId?: ObjectId | undefined;
  roles: UserRole[];
}

export interface TeacherProfile {
  firstName: string;
  lastName: string;
  gender: string;
  email: string;
  personalEmail: string;
  dateOfBirth: Date | undefined;
  phoneNumber: PhoneNumber | undefined;
}

function createBaseTeacherBasic(): TeacherBasic {
  return {
    id: undefined,
    organization: undefined,
    username: "",
    emailDomain: "",
    email: "",
    firstName: "",
    lastName: "",
  };
}

export const TeacherBasic: MessageFns<TeacherBasic> = {
  encode(message: TeacherBasic, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      ObjectId.encode(message.id, writer.uint32(10).fork()).join();
    }
    if (message.organization !== undefined) {
      ObjectId.encode(message.organization, writer.uint32(18).fork()).join();
    }
    if (message.username !== "") {
      writer.uint32(26).string(message.username);
    }
    if (message.emailDomain !== "") {
      writer.uint32(34).string(message.emailDomain);
    }
    if (message.email !== "") {
      writer.uint32(42).string(message.email);
    }
    if (message.firstName !== "") {
      writer.uint32(50).string(message.firstName);
    }
    if (message.lastName !== "") {
      writer.uint32(58).string(message.lastName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TeacherBasic {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTeacherBasic();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.organization = ObjectId.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.username = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.emailDomain = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.email = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.firstName = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.lastName = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TeacherBasic {
    return {
      id: isSet(object.id) ? ObjectId.fromJSON(object.id) : undefined,
      organization: isSet(object.organization) ? ObjectId.fromJSON(object.organization) : undefined,
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      emailDomain: isSet(object.emailDomain) ? globalThis.String(object.emailDomain) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      firstName: isSet(object.firstName) ? globalThis.String(object.firstName) : "",
      lastName: isSet(object.lastName) ? globalThis.String(object.lastName) : "",
    };
  },

  toJSON(message: TeacherBasic): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = ObjectId.toJSON(message.id);
    }
    if (message.organization !== undefined) {
      obj.organization = ObjectId.toJSON(message.organization);
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.emailDomain !== "") {
      obj.emailDomain = message.emailDomain;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.firstName !== "") {
      obj.firstName = message.firstName;
    }
    if (message.lastName !== "") {
      obj.lastName = message.lastName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TeacherBasic>, I>>(base?: I): TeacherBasic {
    return TeacherBasic.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TeacherBasic>, I>>(object: I): TeacherBasic {
    const message = createBaseTeacherBasic();
    message.id = (object.id !== undefined && object.id !== null) ? ObjectId.fromPartial(object.id) : undefined;
    message.organization = (object.organization !== undefined && object.organization !== null)
      ? ObjectId.fromPartial(object.organization)
      : undefined;
    message.username = object.username ?? "";
    message.emailDomain = object.emailDomain ?? "";
    message.email = object.email ?? "";
    message.firstName = object.firstName ?? "";
    message.lastName = object.lastName ?? "";
    return message;
  },
};

function createBaseTeacher(): Teacher {
  return {
    id: undefined,
    status: TeacherStatus.ACTIVE,
    username: "",
    emailDomain: "",
    firstName: "",
    lastName: "",
    gender: "",
    email: "",
    personalEmail: "",
    dateOfBirth: undefined,
    phoneNumber: undefined,
    signatureFileId: undefined,
    roles: [],
  };
}

export const Teacher: MessageFns<Teacher> = {
  encode(message: Teacher, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      ObjectId.encode(message.id, writer.uint32(10).fork()).join();
    }
    if (message.status !== TeacherStatus.ACTIVE) {
      writer.uint32(16).int32(teacherStatusToNumber(message.status));
    }
    if (message.username !== "") {
      writer.uint32(26).string(message.username);
    }
    if (message.emailDomain !== "") {
      writer.uint32(34).string(message.emailDomain);
    }
    if (message.firstName !== "") {
      writer.uint32(42).string(message.firstName);
    }
    if (message.lastName !== "") {
      writer.uint32(50).string(message.lastName);
    }
    if (message.gender !== "") {
      writer.uint32(58).string(message.gender);
    }
    if (message.email !== "") {
      writer.uint32(66).string(message.email);
    }
    if (message.personalEmail !== "") {
      writer.uint32(74).string(message.personalEmail);
    }
    if (message.dateOfBirth !== undefined) {
      Timestamp.encode(toTimestamp(message.dateOfBirth), writer.uint32(82).fork()).join();
    }
    if (message.phoneNumber !== undefined) {
      PhoneNumber.encode(message.phoneNumber, writer.uint32(90).fork()).join();
    }
    if (message.signatureFileId !== undefined) {
      ObjectId.encode(message.signatureFileId, writer.uint32(98).fork()).join();
    }
    writer.uint32(122).fork();
    for (const v of message.roles) {
      writer.int32(userRoleToNumber(v));
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Teacher {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTeacher();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = ObjectId.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.status = teacherStatusFromJSON(reader.int32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.username = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.emailDomain = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.firstName = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.lastName = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.gender = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.email = reader.string();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.personalEmail = reader.string();
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.dateOfBirth = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.phoneNumber = PhoneNumber.decode(reader, reader.uint32());
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.signatureFileId = ObjectId.decode(reader, reader.uint32());
          continue;
        case 15:
          if (tag === 120) {
            message.roles.push(userRoleFromJSON(reader.int32()));

            continue;
          }

          if (tag === 122) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.roles.push(userRoleFromJSON(reader.int32()));
            }

            continue;
          }

          break;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Teacher {
    return {
      id: isSet(object.id) ? ObjectId.fromJSON(object.id) : undefined,
      status: isSet(object.status) ? teacherStatusFromJSON(object.status) : TeacherStatus.ACTIVE,
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      emailDomain: isSet(object.emailDomain) ? globalThis.String(object.emailDomain) : "",
      firstName: isSet(object.firstName) ? globalThis.String(object.firstName) : "",
      lastName: isSet(object.lastName) ? globalThis.String(object.lastName) : "",
      gender: isSet(object.gender) ? globalThis.String(object.gender) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      personalEmail: isSet(object.personalEmail) ? globalThis.String(object.personalEmail) : "",
      dateOfBirth: isSet(object.dateOfBirth) ? fromJsonTimestamp(object.dateOfBirth) : undefined,
      phoneNumber: isSet(object.phoneNumber) ? PhoneNumber.fromJSON(object.phoneNumber) : undefined,
      signatureFileId: isSet(object.signatureFileId) ? ObjectId.fromJSON(object.signatureFileId) : undefined,
      roles: globalThis.Array.isArray(object?.roles) ? object.roles.map((e: any) => userRoleFromJSON(e)) : [],
    };
  },

  toJSON(message: Teacher): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = ObjectId.toJSON(message.id);
    }
    if (message.status !== TeacherStatus.ACTIVE) {
      obj.status = teacherStatusToJSON(message.status);
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.emailDomain !== "") {
      obj.emailDomain = message.emailDomain;
    }
    if (message.firstName !== "") {
      obj.firstName = message.firstName;
    }
    if (message.lastName !== "") {
      obj.lastName = message.lastName;
    }
    if (message.gender !== "") {
      obj.gender = message.gender;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.personalEmail !== "") {
      obj.personalEmail = message.personalEmail;
    }
    if (message.dateOfBirth !== undefined) {
      obj.dateOfBirth = message.dateOfBirth.toISOString();
    }
    if (message.phoneNumber !== undefined) {
      obj.phoneNumber = PhoneNumber.toJSON(message.phoneNumber);
    }
    if (message.signatureFileId !== undefined) {
      obj.signatureFileId = ObjectId.toJSON(message.signatureFileId);
    }
    if (message.roles?.length) {
      obj.roles = message.roles.map((e) => userRoleToJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Teacher>, I>>(base?: I): Teacher {
    return Teacher.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Teacher>, I>>(object: I): Teacher {
    const message = createBaseTeacher();
    message.id = (object.id !== undefined && object.id !== null) ? ObjectId.fromPartial(object.id) : undefined;
    message.status = object.status ?? TeacherStatus.ACTIVE;
    message.username = object.username ?? "";
    message.emailDomain = object.emailDomain ?? "";
    message.firstName = object.firstName ?? "";
    message.lastName = object.lastName ?? "";
    message.gender = object.gender ?? "";
    message.email = object.email ?? "";
    message.personalEmail = object.personalEmail ?? "";
    message.dateOfBirth = object.dateOfBirth ?? undefined;
    message.phoneNumber = (object.phoneNumber !== undefined && object.phoneNumber !== null)
      ? PhoneNumber.fromPartial(object.phoneNumber)
      : undefined;
    message.signatureFileId = (object.signatureFileId !== undefined && object.signatureFileId !== null)
      ? ObjectId.fromPartial(object.signatureFileId)
      : undefined;
    message.roles = object.roles?.map((e) => e) || [];
    return message;
  },
};

function createBaseTeacherProfile(): TeacherProfile {
  return {
    firstName: "",
    lastName: "",
    gender: "",
    email: "",
    personalEmail: "",
    dateOfBirth: undefined,
    phoneNumber: undefined,
  };
}

export const TeacherProfile: MessageFns<TeacherProfile> = {
  encode(message: TeacherProfile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.firstName !== "") {
      writer.uint32(10).string(message.firstName);
    }
    if (message.lastName !== "") {
      writer.uint32(18).string(message.lastName);
    }
    if (message.gender !== "") {
      writer.uint32(26).string(message.gender);
    }
    if (message.email !== "") {
      writer.uint32(34).string(message.email);
    }
    if (message.personalEmail !== "") {
      writer.uint32(42).string(message.personalEmail);
    }
    if (message.dateOfBirth !== undefined) {
      Timestamp.encode(toTimestamp(message.dateOfBirth), writer.uint32(50).fork()).join();
    }
    if (message.phoneNumber !== undefined) {
      PhoneNumber.encode(message.phoneNumber, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TeacherProfile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTeacherProfile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.firstName = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.lastName = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.gender = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.email = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.personalEmail = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.dateOfBirth = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.phoneNumber = PhoneNumber.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TeacherProfile {
    return {
      firstName: isSet(object.firstName) ? globalThis.String(object.firstName) : "",
      lastName: isSet(object.lastName) ? globalThis.String(object.lastName) : "",
      gender: isSet(object.gender) ? globalThis.String(object.gender) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      personalEmail: isSet(object.personalEmail) ? globalThis.String(object.personalEmail) : "",
      dateOfBirth: isSet(object.dateOfBirth) ? fromJsonTimestamp(object.dateOfBirth) : undefined,
      phoneNumber: isSet(object.phoneNumber) ? PhoneNumber.fromJSON(object.phoneNumber) : undefined,
    };
  },

  toJSON(message: TeacherProfile): unknown {
    const obj: any = {};
    if (message.firstName !== "") {
      obj.firstName = message.firstName;
    }
    if (message.lastName !== "") {
      obj.lastName = message.lastName;
    }
    if (message.gender !== "") {
      obj.gender = message.gender;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.personalEmail !== "") {
      obj.personalEmail = message.personalEmail;
    }
    if (message.dateOfBirth !== undefined) {
      obj.dateOfBirth = message.dateOfBirth.toISOString();
    }
    if (message.phoneNumber !== undefined) {
      obj.phoneNumber = PhoneNumber.toJSON(message.phoneNumber);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TeacherProfile>, I>>(base?: I): TeacherProfile {
    return TeacherProfile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TeacherProfile>, I>>(object: I): TeacherProfile {
    const message = createBaseTeacherProfile();
    message.firstName = object.firstName ?? "";
    message.lastName = object.lastName ?? "";
    message.gender = object.gender ?? "";
    message.email = object.email ?? "";
    message.personalEmail = object.personalEmail ?? "";
    message.dateOfBirth = object.dateOfBirth ?? undefined;
    message.phoneNumber = (object.phoneNumber !== undefined && object.phoneNumber !== null)
      ? PhoneNumber.fromPartial(object.phoneNumber)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
